//
// Generated by JavaToPas v1.5 20160510 - 150155
////////////////////////////////////////////////////////////////////////////////
unit android.text.style.ScaleXSpan;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os,
  android.text.TextPaint;

type
  JScaleXSpan = interface;

  JScaleXSpanClass = interface(JObjectClass)
    ['{4561C345-4321-4E02-9911-A9F514F3A47C}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function getScaleX : Single; cdecl;                                         // ()F A: $1
    function getSpanTypeId : Integer; cdecl;                                    // ()I A: $1
    function init(proportion : Single) : JScaleXSpan; cdecl; overload;          // (F)V A: $1
    function init(src : JParcel) : JScaleXSpan; cdecl; overload;                // (Landroid/os/Parcel;)V A: $1
    procedure updateDrawState(ds : JTextPaint) ; cdecl;                         // (Landroid/text/TextPaint;)V A: $1
    procedure updateMeasureState(ds : JTextPaint) ; cdecl;                      // (Landroid/text/TextPaint;)V A: $1
    procedure writeToParcel(dest : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  [JavaSignature('android/text/style/ScaleXSpan')]
  JScaleXSpan = interface(JObject)
    ['{CB287314-2FDB-4C05-95A6-9FF2F731E7E7}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function getScaleX : Single; cdecl;                                         // ()F A: $1
    function getSpanTypeId : Integer; cdecl;                                    // ()I A: $1
    procedure updateDrawState(ds : JTextPaint) ; cdecl;                         // (Landroid/text/TextPaint;)V A: $1
    procedure updateMeasureState(ds : JTextPaint) ; cdecl;                      // (Landroid/text/TextPaint;)V A: $1
    procedure writeToParcel(dest : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  TJScaleXSpan = class(TJavaGenericImport<JScaleXSpanClass, JScaleXSpan>)
  end;

implementation

end.
