//
// Generated by JavaToPas v1.5 20160510 - 150119
////////////////////////////////////////////////////////////////////////////////
unit android.os.health.ProcessHealthStats;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JProcessHealthStats = interface;

  JProcessHealthStatsClass = interface(JObjectClass)
    ['{9CCEDB11-B59B-447E-8DB9-59EA2BD34C3D}']
    function _GetMEASUREMENT_ANR_COUNT : Integer; cdecl;                        //  A: $19
    function _GetMEASUREMENT_CRASHES_COUNT : Integer; cdecl;                    //  A: $19
    function _GetMEASUREMENT_FOREGROUND_MS : Integer; cdecl;                    //  A: $19
    function _GetMEASUREMENT_STARTS_COUNT : Integer; cdecl;                     //  A: $19
    function _GetMEASUREMENT_SYSTEM_TIME_MS : Integer; cdecl;                   //  A: $19
    function _GetMEASUREMENT_USER_TIME_MS : Integer; cdecl;                     //  A: $19
    property MEASUREMENT_ANR_COUNT : Integer read _GetMEASUREMENT_ANR_COUNT;    // I A: $19
    property MEASUREMENT_CRASHES_COUNT : Integer read _GetMEASUREMENT_CRASHES_COUNT;// I A: $19
    property MEASUREMENT_FOREGROUND_MS : Integer read _GetMEASUREMENT_FOREGROUND_MS;// I A: $19
    property MEASUREMENT_STARTS_COUNT : Integer read _GetMEASUREMENT_STARTS_COUNT;// I A: $19
    property MEASUREMENT_SYSTEM_TIME_MS : Integer read _GetMEASUREMENT_SYSTEM_TIME_MS;// I A: $19
    property MEASUREMENT_USER_TIME_MS : Integer read _GetMEASUREMENT_USER_TIME_MS;// I A: $19
  end;

  [JavaSignature('android/os/health/ProcessHealthStats')]
  JProcessHealthStats = interface(JObject)
    ['{BFE5ED7D-2CBD-4039-860E-24B2F87D51AE}']
  end;

  TJProcessHealthStats = class(TJavaGenericImport<JProcessHealthStatsClass, JProcessHealthStats>)
  end;

const
  TJProcessHealthStatsMEASUREMENT_ANR_COUNT = 30005;
  TJProcessHealthStatsMEASUREMENT_CRASHES_COUNT = 30004;
  TJProcessHealthStatsMEASUREMENT_FOREGROUND_MS = 30006;
  TJProcessHealthStatsMEASUREMENT_STARTS_COUNT = 30003;
  TJProcessHealthStatsMEASUREMENT_SYSTEM_TIME_MS = 30002;
  TJProcessHealthStatsMEASUREMENT_USER_TIME_MS = 30001;

implementation

end.
