//
// Generated by JavaToPas v1.5 20160510 - 150157
////////////////////////////////////////////////////////////////////////////////
unit android.text.Layout_Directions;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JLayout_Directions = interface;

  JLayout_DirectionsClass = interface(JObjectClass)
    ['{21D7D89A-7A33-4C72-B32D-36131B5DEA0E}']
  end;

  [JavaSignature('android/text/Layout_Directions')]
  JLayout_Directions = interface(JObject)
    ['{DC1DEF1A-EDCC-46CA-9535-82BFC6B02CCB}']
  end;

  TJLayout_Directions = class(TJavaGenericImport<JLayout_DirectionsClass, JLayout_Directions>)
  end;

implementation

end.
