//
// Generated by JavaToPas v1.5 20160510 - 150119
////////////////////////////////////////////////////////////////////////////////
unit android.os.storage.StorageManager;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os;

type
  JStorageManager = interface;

  JStorageManagerClass = interface(JObjectClass)
    ['{619A756D-89BD-4F12-956E-8F93B4EF123A}']
    function getMountedObbPath(rawPath : JString) : JString; cdecl;             // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function getPrimaryStorageVolume : JStorageVolume; cdecl;                   // ()Landroid/os/storage/StorageVolume; A: $1
    function getStorageVolumes : JList; cdecl;                                  // ()Ljava/util/List; A: $1
    function isEncrypted(&file : JFile) : boolean; cdecl;                       // (Ljava/io/File;)Z A: $1
    function isObbMounted(rawPath : JString) : boolean; cdecl;                  // (Ljava/lang/String;)Z A: $1
    function mountObb(rawPath : JString; key : JString; listener : JOnObbStateChangeListener) : boolean; cdecl;// (Ljava/lang/String;Ljava/lang/String;Landroid/os/storage/OnObbStateChangeListener;)Z A: $1
    function unmountObb(rawPath : JString; force : boolean; listener : JOnObbStateChangeListener) : boolean; cdecl;// (Ljava/lang/String;ZLandroid/os/storage/OnObbStateChangeListener;)Z A: $1
  end;

  [JavaSignature('android/os/storage/StorageManager')]
  JStorageManager = interface(JObject)
    ['{3F864E1B-00E6-438D-9BA1-000B82370AA4}']
    function getMountedObbPath(rawPath : JString) : JString; cdecl;             // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function getPrimaryStorageVolume : JStorageVolume; cdecl;                   // ()Landroid/os/storage/StorageVolume; A: $1
    function getStorageVolumes : JList; cdecl;                                  // ()Ljava/util/List; A: $1
    function isEncrypted(&file : JFile) : boolean; cdecl;                       // (Ljava/io/File;)Z A: $1
    function isObbMounted(rawPath : JString) : boolean; cdecl;                  // (Ljava/lang/String;)Z A: $1
    function mountObb(rawPath : JString; key : JString; listener : JOnObbStateChangeListener) : boolean; cdecl;// (Ljava/lang/String;Ljava/lang/String;Landroid/os/storage/OnObbStateChangeListener;)Z A: $1
    function unmountObb(rawPath : JString; force : boolean; listener : JOnObbStateChangeListener) : boolean; cdecl;// (Ljava/lang/String;ZLandroid/os/storage/OnObbStateChangeListener;)Z A: $1
  end;

  TJStorageManager = class(TJavaGenericImport<JStorageManagerClass, JStorageManager>)
  end;

implementation

end.
