//
// Generated by JavaToPas v1.5 20160510 - 150029
////////////////////////////////////////////////////////////////////////////////
unit java.lang.Error;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JError = interface;

  JErrorClass = interface(JObjectClass)
    ['{8CF392E6-9CA4-4B0D-8149-C7D80E8E7DEF}']
    function init : JError; cdecl; overload;                                    // ()V A: $1
    function init(&message : JString) : JError; cdecl; overload;                // (Ljava/lang/String;)V A: $1
    function init(&message : JString; cause : JThrowable) : JError; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Throwable;)V A: $1
    function init(cause : JThrowable) : JError; cdecl; overload;                // (Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('java/lang/Error')]
  JError = interface(JObject)
    ['{D3889BCC-1EB7-4424-866F-E2831AAC9CFA}']
  end;

  TJError = class(TJavaGenericImport<JErrorClass, JError>)
  end;

implementation

end.
