//
// Generated by JavaToPas v1.4 20140515 - 181135
////////////////////////////////////////////////////////////////////////////////
unit java.util.FormattableFlags;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JFormattableFlags = interface;

  JFormattableFlagsClass = interface(JObjectClass)
    ['{20BF885A-11B1-455F-9BDB-6200F31386BF}']
    function _GetALTERNATE : Integer; cdecl;                                    //  A: $19
    function _GetLEFT_JUSTIFY : Integer; cdecl;                                 //  A: $19
    function _GetUPPERCASE : Integer; cdecl;                                    //  A: $19
    property ALTERNATE : Integer read _GetALTERNATE;                            // I A: $19
    property LEFT_JUSTIFY : Integer read _GetLEFT_JUSTIFY;                      // I A: $19
    property UPPERCASE : Integer read _GetUPPERCASE;                            // I A: $19
  end;

  [JavaSignature('java/util/FormattableFlags')]
  JFormattableFlags = interface(JObject)
    ['{CADE54F6-8292-4966-9349-A737A73074DB}']
  end;

  TJFormattableFlags = class(TJavaGenericImport<JFormattableFlagsClass, JFormattableFlags>)
  end;

const
  TJFormattableFlagsLEFT_JUSTIFY = 1;
  TJFormattableFlagsUPPERCASE = 2;
  TJFormattableFlagsALTERNATE = 4;

implementation

end.
