//
// Generated by JavaToPas v1.4 20140515 - 183222
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.client.params.CookiePolicy;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JCookiePolicy = interface;

  JCookiePolicyClass = interface(JObjectClass)
    ['{1262FDA0-40A5-4A5B-9E89-CF682669A3BA}']
    function _GetBEST_MATCH : JString; cdecl;                                   //  A: $19
    function _GetBROWSER_COMPATIBILITY : JString; cdecl;                        //  A: $19
    function _GetNETSCAPE : JString; cdecl;                                     //  A: $19
    function _GetRFC_2109 : JString; cdecl;                                     //  A: $19
    function _GetRFC_2965 : JString; cdecl;                                     //  A: $19
    property BEST_MATCH : JString read _GetBEST_MATCH;                          // Ljava/lang/String; A: $19
    property BROWSER_COMPATIBILITY : JString read _GetBROWSER_COMPATIBILITY;    // Ljava/lang/String; A: $19
    property NETSCAPE : JString read _GetNETSCAPE;                              // Ljava/lang/String; A: $19
    property RFC_2109 : JString read _GetRFC_2109;                              // Ljava/lang/String; A: $19
    property RFC_2965 : JString read _GetRFC_2965;                              // Ljava/lang/String; A: $19
  end;

  [JavaSignature('org/apache/http/client/params/CookiePolicy')]
  JCookiePolicy = interface(JObject)
    ['{4833F116-DDE3-4B99-B954-CBC4DD0B5625}']
  end;

  TJCookiePolicy = class(TJavaGenericImport<JCookiePolicyClass, JCookiePolicy>)
  end;

const
  TJCookiePolicyBROWSER_COMPATIBILITY = 'compatibility';
  TJCookiePolicyNETSCAPE = 'netscape';
  TJCookiePolicyRFC_2109 = 'rfc2109';
  TJCookiePolicyRFC_2965 = 'rfc2965';
  TJCookiePolicyBEST_MATCH = 'best-match';

implementation

end.
