//
// Generated by JavaToPas v1.5 20150830 - 104052
////////////////////////////////////////////////////////////////////////////////
unit android.hardware.display.VirtualDisplay;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.view.Display,
  android.view.Surface;

type
  JVirtualDisplay = interface;

  JVirtualDisplayClass = interface(JObjectClass)
    ['{2A19EE3C-C11A-4DB7-A619-A5F40055EC88}']
    function getDisplay : JDisplay; cdecl;                                      // ()Landroid/view/Display; A: $1
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure release ; cdecl;                                                  // ()V A: $1
    procedure resize(width : Integer; height : Integer; densityDpi : Integer) ; cdecl;// (III)V A: $1
    procedure setSurface(surface : JSurface) ; cdecl;                           // (Landroid/view/Surface;)V A: $1
  end;

  [JavaSignature('android/hardware/display/VirtualDisplay$Callback')]
  JVirtualDisplay = interface(JObject)
    ['{A2D73A68-611F-44C5-AC1A-0AC3CA57A932}']
    function getDisplay : JDisplay; cdecl;                                      // ()Landroid/view/Display; A: $1
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure release ; cdecl;                                                  // ()V A: $1
    procedure resize(width : Integer; height : Integer; densityDpi : Integer) ; cdecl;// (III)V A: $1
    procedure setSurface(surface : JSurface) ; cdecl;                           // (Landroid/view/Surface;)V A: $1
  end;

  TJVirtualDisplay = class(TJavaGenericImport<JVirtualDisplayClass, JVirtualDisplay>)
  end;

implementation

end.
