//
// Generated by JavaToPas v1.5 20150830 - 104142
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.message.HeaderValueParser;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.apache.http.HeaderElement,
  org.apache.http.util.ByteArrayBuffer,
  org.apache.http.message.ParserCursor,
  org.apache.http.NameValuePair;

type
  JHeaderValueParser = interface;

  JHeaderValueParserClass = interface(JObjectClass)
    ['{1B770026-A47D-41CD-BF41-7D2CFC9D1B9A}']
    function parseElements(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : TJavaArray<JHeaderElement>; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)[Lorg/apache/http/HeaderElement; A: $401
    function parseHeaderElement(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JHeaderElement; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/HeaderElement; A: $401
    function parseNameValuePair(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JNameValuePair; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/NameValuePair; A: $401
    function parseParameters(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : TJavaArray<JNameValuePair>; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)[Lorg/apache/http/NameValuePair; A: $401
  end;

  [JavaSignature('org/apache/http/message/HeaderValueParser')]
  JHeaderValueParser = interface(JObject)
    ['{3D05D61A-5DE6-4BC0-9F23-6EBEAF30387F}']
    function parseElements(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : TJavaArray<JHeaderElement>; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)[Lorg/apache/http/HeaderElement; A: $401
    function parseHeaderElement(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JHeaderElement; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/HeaderElement; A: $401
    function parseNameValuePair(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JNameValuePair; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/NameValuePair; A: $401
    function parseParameters(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : TJavaArray<JNameValuePair>; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)[Lorg/apache/http/NameValuePair; A: $401
  end;

  TJHeaderValueParser = class(TJavaGenericImport<JHeaderValueParserClass, JHeaderValueParser>)
  end;

implementation

end.
