//
// Generated by JavaToPas v1.4 20140515 - 182439
////////////////////////////////////////////////////////////////////////////////
unit android.media.MediaRouter_RouteGroup;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.media.MediaRouter_RouteInfo,
  android.graphics.drawable.Drawable;

type
  JMediaRouter_RouteGroup = interface;

  JMediaRouter_RouteGroupClass = interface(JObjectClass)
    ['{97432C03-D012-4807-AB68-ED31282338CA}']
    function getRouteAt(&index : Integer) : JMediaRouter_RouteInfo; cdecl;      // (I)Landroid/media/MediaRouter$RouteInfo; A: $1
    function getRouteCount : Integer; cdecl;                                    // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure addRoute(route : JMediaRouter_RouteInfo) ; cdecl; overload;       // (Landroid/media/MediaRouter$RouteInfo;)V A: $1
    procedure addRoute(route : JMediaRouter_RouteInfo; insertAt : Integer) ; cdecl; overload;// (Landroid/media/MediaRouter$RouteInfo;I)V A: $1
    procedure removeRoute(&index : Integer) ; cdecl; overload;                  // (I)V A: $1
    procedure removeRoute(route : JMediaRouter_RouteInfo) ; cdecl; overload;    // (Landroid/media/MediaRouter$RouteInfo;)V A: $1
    procedure requestSetVolume(volume : Integer) ; cdecl;                       // (I)V A: $1
    procedure requestUpdateVolume(direction : Integer) ; cdecl;                 // (I)V A: $1
    procedure setIconDrawable(icon : JDrawable) ; cdecl;                        // (Landroid/graphics/drawable/Drawable;)V A: $1
    procedure setIconResource(resId : Integer) ; cdecl;                         // (I)V A: $1
  end;

  [JavaSignature('android/media/MediaRouter_RouteGroup')]
  JMediaRouter_RouteGroup = interface(JObject)
    ['{0A943E35-C7D8-4C50-92FD-21899DAD1468}']
    function getRouteAt(&index : Integer) : JMediaRouter_RouteInfo; cdecl;      // (I)Landroid/media/MediaRouter$RouteInfo; A: $1
    function getRouteCount : Integer; cdecl;                                    // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure addRoute(route : JMediaRouter_RouteInfo) ; cdecl; overload;       // (Landroid/media/MediaRouter$RouteInfo;)V A: $1
    procedure addRoute(route : JMediaRouter_RouteInfo; insertAt : Integer) ; cdecl; overload;// (Landroid/media/MediaRouter$RouteInfo;I)V A: $1
    procedure removeRoute(&index : Integer) ; cdecl; overload;                  // (I)V A: $1
    procedure removeRoute(route : JMediaRouter_RouteInfo) ; cdecl; overload;    // (Landroid/media/MediaRouter$RouteInfo;)V A: $1
    procedure requestSetVolume(volume : Integer) ; cdecl;                       // (I)V A: $1
    procedure requestUpdateVolume(direction : Integer) ; cdecl;                 // (I)V A: $1
    procedure setIconDrawable(icon : JDrawable) ; cdecl;                        // (Landroid/graphics/drawable/Drawable;)V A: $1
    procedure setIconResource(resId : Integer) ; cdecl;                         // (I)V A: $1
  end;

  TJMediaRouter_RouteGroup = class(TJavaGenericImport<JMediaRouter_RouteGroupClass, JMediaRouter_RouteGroup>)
  end;

implementation

end.
