//
// Generated by JavaToPas v1.4 20140515 - 182114
////////////////////////////////////////////////////////////////////////////////
unit android.provider.ContactsContract_RawContactsEntity;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.net.Uri;

type
  JContactsContract_RawContactsEntity = interface;

  JContactsContract_RawContactsEntityClass = interface(JObjectClass)
    ['{C18EDE8C-C1D0-47E8-A607-86835B9B500E}']
    function _GetCONTENT_TYPE : JString; cdecl;                                 //  A: $19
    function _GetCONTENT_URI : JUri; cdecl;                                     //  A: $19
    function _GetDATA_ID : JString; cdecl;                                      //  A: $19
    function _GetPROFILE_CONTENT_URI : JUri; cdecl;                             //  A: $19
    property CONTENT_TYPE : JString read _GetCONTENT_TYPE;                      // Ljava/lang/String; A: $19
    property CONTENT_URI : JUri read _GetCONTENT_URI;                           // Landroid/net/Uri; A: $19
    property DATA_ID : JString read _GetDATA_ID;                                // Ljava/lang/String; A: $19
    property PROFILE_CONTENT_URI : JUri read _GetPROFILE_CONTENT_URI;           // Landroid/net/Uri; A: $19
  end;

  [JavaSignature('android/provider/ContactsContract_RawContactsEntity')]
  JContactsContract_RawContactsEntity = interface(JObject)
    ['{25777ADD-3538-476D-AFD2-FBF6CD629DF2}']
  end;

  TJContactsContract_RawContactsEntity = class(TJavaGenericImport<JContactsContract_RawContactsEntityClass, JContactsContract_RawContactsEntity>)
  end;

const
  TJContactsContract_RawContactsEntityCONTENT_TYPE = 'vnd.android.cursor.dir/raw_contact_entity';
  TJContactsContract_RawContactsEntityDATA_ID = 'data_id';

implementation

end.
