//
// Generated by JavaToPas v1.4 20140515 - 182000
////////////////////////////////////////////////////////////////////////////////
unit android.bluetooth.BluetoothAdapter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.bluetooth.BluetoothDevice,
  android.bluetooth.BluetoothServerSocket,
  Androidapi.JNI.GraphicsContentViewText,
  android.bluetooth.BluetoothProfile_ServiceListener,
  android.bluetooth.BluetoothProfile;

type
  JBluetoothAdapter = interface;

  JBluetoothAdapterClass = interface(JObjectClass)
    ['{CA7105E8-C8D2-4D3F-B4BF-FAB72B909609}']
    function _GetACTION_CONNECTION_STATE_CHANGED : JString; cdecl;              //  A: $19
    function _GetACTION_DISCOVERY_FINISHED : JString; cdecl;                    //  A: $19
    function _GetACTION_DISCOVERY_STARTED : JString; cdecl;                     //  A: $19
    function _GetACTION_LOCAL_NAME_CHANGED : JString; cdecl;                    //  A: $19
    function _GetACTION_REQUEST_DISCOVERABLE : JString; cdecl;                  //  A: $19
    function _GetACTION_REQUEST_ENABLE : JString; cdecl;                        //  A: $19
    function _GetACTION_SCAN_MODE_CHANGED : JString; cdecl;                     //  A: $19
    function _GetACTION_STATE_CHANGED : JString; cdecl;                         //  A: $19
    function _GetERROR : Integer; cdecl;                                        //  A: $19
    function _GetEXTRA_CONNECTION_STATE : JString; cdecl;                       //  A: $19
    function _GetEXTRA_DISCOVERABLE_DURATION : JString; cdecl;                  //  A: $19
    function _GetEXTRA_LOCAL_NAME : JString; cdecl;                             //  A: $19
    function _GetEXTRA_PREVIOUS_CONNECTION_STATE : JString; cdecl;              //  A: $19
    function _GetEXTRA_PREVIOUS_SCAN_MODE : JString; cdecl;                     //  A: $19
    function _GetEXTRA_PREVIOUS_STATE : JString; cdecl;                         //  A: $19
    function _GetEXTRA_SCAN_MODE : JString; cdecl;                              //  A: $19
    function _GetEXTRA_STATE : JString; cdecl;                                  //  A: $19
    function _GetSCAN_MODE_CONNECTABLE : Integer; cdecl;                        //  A: $19
    function _GetSCAN_MODE_CONNECTABLE_DISCOVERABLE : Integer; cdecl;           //  A: $19
    function _GetSCAN_MODE_NONE : Integer; cdecl;                               //  A: $19
    function _GetSTATE_CONNECTED : Integer; cdecl;                              //  A: $19
    function _GetSTATE_CONNECTING : Integer; cdecl;                             //  A: $19
    function _GetSTATE_DISCONNECTED : Integer; cdecl;                           //  A: $19
    function _GetSTATE_DISCONNECTING : Integer; cdecl;                          //  A: $19
    function _GetSTATE_OFF : Integer; cdecl;                                    //  A: $19
    function _GetSTATE_ON : Integer; cdecl;                                     //  A: $19
    function _GetSTATE_TURNING_OFF : Integer; cdecl;                            //  A: $19
    function _GetSTATE_TURNING_ON : Integer; cdecl;                             //  A: $19
    function cancelDiscovery : boolean; cdecl;                                  // ()Z A: $1
    function checkBluetoothAddress(address : JString) : boolean; cdecl;         // (Ljava/lang/String;)Z A: $9
    function disable : boolean; cdecl;                                          // ()Z A: $1
    function enable : boolean; cdecl;                                           // ()Z A: $1
    function getAddress : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getBondedDevices : JSet; cdecl;                                    // ()Ljava/util/Set; A: $1
    function getDefaultAdapter : JBluetoothAdapter; cdecl;                      // ()Landroid/bluetooth/BluetoothAdapter; A: $29
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getProfileConnectionState(profile : Integer) : Integer; cdecl;     // (I)I A: $1
    function getProfileProxy(context : JContext; listener : JBluetoothProfile_ServiceListener; profile : Integer) : boolean; cdecl;// (Landroid/content/Context;Landroid/bluetooth/BluetoothProfile$ServiceListener;I)Z A: $1
    function getRemoteDevice(address : JString) : JBluetoothDevice; cdecl; overload;// (Ljava/lang/String;)Landroid/bluetooth/BluetoothDevice; A: $1
    function getRemoteDevice(address : TJavaArray<Byte>) : JBluetoothDevice; cdecl; overload;// ([B)Landroid/bluetooth/BluetoothDevice; A: $1
    function getScanMode : Integer; cdecl;                                      // ()I A: $1
    function getState : Integer; cdecl;                                         // ()I A: $1
    function isDiscovering : boolean; cdecl;                                    // ()Z A: $1
    function isEnabled : boolean; cdecl;                                        // ()Z A: $1
    function listenUsingInsecureRfcommWithServiceRecord(&name : JString; uuid : JUUID) : JBluetoothServerSocket; cdecl;// (Ljava/lang/String;Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket; A: $1
    function listenUsingRfcommWithServiceRecord(&name : JString; uuid : JUUID) : JBluetoothServerSocket; cdecl;// (Ljava/lang/String;Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket; A: $1
    function setName(&name : JString) : boolean; cdecl;                         // (Ljava/lang/String;)Z A: $1
    function startDiscovery : boolean; cdecl;                                   // ()Z A: $1
    procedure closeProfileProxy(profile : Integer; proxy : JBluetoothProfile) ; cdecl;// (ILandroid/bluetooth/BluetoothProfile;)V A: $1
    property ACTION_CONNECTION_STATE_CHANGED : JString read _GetACTION_CONNECTION_STATE_CHANGED;// Ljava/lang/String; A: $19
    property ACTION_DISCOVERY_FINISHED : JString read _GetACTION_DISCOVERY_FINISHED;// Ljava/lang/String; A: $19
    property ACTION_DISCOVERY_STARTED : JString read _GetACTION_DISCOVERY_STARTED;// Ljava/lang/String; A: $19
    property ACTION_LOCAL_NAME_CHANGED : JString read _GetACTION_LOCAL_NAME_CHANGED;// Ljava/lang/String; A: $19
    property ACTION_REQUEST_DISCOVERABLE : JString read _GetACTION_REQUEST_DISCOVERABLE;// Ljava/lang/String; A: $19
    property ACTION_REQUEST_ENABLE : JString read _GetACTION_REQUEST_ENABLE;    // Ljava/lang/String; A: $19
    property ACTION_SCAN_MODE_CHANGED : JString read _GetACTION_SCAN_MODE_CHANGED;// Ljava/lang/String; A: $19
    property ACTION_STATE_CHANGED : JString read _GetACTION_STATE_CHANGED;      // Ljava/lang/String; A: $19
    property ERROR : Integer read _GetERROR;                                    // I A: $19
    property EXTRA_CONNECTION_STATE : JString read _GetEXTRA_CONNECTION_STATE;  // Ljava/lang/String; A: $19
    property EXTRA_DISCOVERABLE_DURATION : JString read _GetEXTRA_DISCOVERABLE_DURATION;// Ljava/lang/String; A: $19
    property EXTRA_LOCAL_NAME : JString read _GetEXTRA_LOCAL_NAME;              // Ljava/lang/String; A: $19
    property EXTRA_PREVIOUS_CONNECTION_STATE : JString read _GetEXTRA_PREVIOUS_CONNECTION_STATE;// Ljava/lang/String; A: $19
    property EXTRA_PREVIOUS_SCAN_MODE : JString read _GetEXTRA_PREVIOUS_SCAN_MODE;// Ljava/lang/String; A: $19
    property EXTRA_PREVIOUS_STATE : JString read _GetEXTRA_PREVIOUS_STATE;      // Ljava/lang/String; A: $19
    property EXTRA_SCAN_MODE : JString read _GetEXTRA_SCAN_MODE;                // Ljava/lang/String; A: $19
    property EXTRA_STATE : JString read _GetEXTRA_STATE;                        // Ljava/lang/String; A: $19
    property SCAN_MODE_CONNECTABLE : Integer read _GetSCAN_MODE_CONNECTABLE;    // I A: $19
    property SCAN_MODE_CONNECTABLE_DISCOVERABLE : Integer read _GetSCAN_MODE_CONNECTABLE_DISCOVERABLE;// I A: $19
    property SCAN_MODE_NONE : Integer read _GetSCAN_MODE_NONE;                  // I A: $19
    property STATE_CONNECTED : Integer read _GetSTATE_CONNECTED;                // I A: $19
    property STATE_CONNECTING : Integer read _GetSTATE_CONNECTING;              // I A: $19
    property STATE_DISCONNECTED : Integer read _GetSTATE_DISCONNECTED;          // I A: $19
    property STATE_DISCONNECTING : Integer read _GetSTATE_DISCONNECTING;        // I A: $19
    property STATE_OFF : Integer read _GetSTATE_OFF;                            // I A: $19
    property STATE_ON : Integer read _GetSTATE_ON;                              // I A: $19
    property STATE_TURNING_OFF : Integer read _GetSTATE_TURNING_OFF;            // I A: $19
    property STATE_TURNING_ON : Integer read _GetSTATE_TURNING_ON;              // I A: $19
  end;

  [JavaSignature('android/bluetooth/BluetoothAdapter')]
  JBluetoothAdapter = interface(JObject)
    ['{228CE522-CFC8-41CC-9425-8E3AD728488E}']
    function cancelDiscovery : boolean; cdecl;                                  // ()Z A: $1
    function disable : boolean; cdecl;                                          // ()Z A: $1
    function enable : boolean; cdecl;                                           // ()Z A: $1
    function getAddress : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getBondedDevices : JSet; cdecl;                                    // ()Ljava/util/Set; A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getProfileConnectionState(profile : Integer) : Integer; cdecl;     // (I)I A: $1
    function getProfileProxy(context : JContext; listener : JBluetoothProfile_ServiceListener; profile : Integer) : boolean; cdecl;// (Landroid/content/Context;Landroid/bluetooth/BluetoothProfile$ServiceListener;I)Z A: $1
    function getRemoteDevice(address : JString) : JBluetoothDevice; cdecl; overload;// (Ljava/lang/String;)Landroid/bluetooth/BluetoothDevice; A: $1
    function getRemoteDevice(address : TJavaArray<Byte>) : JBluetoothDevice; cdecl; overload;// ([B)Landroid/bluetooth/BluetoothDevice; A: $1
    function getScanMode : Integer; cdecl;                                      // ()I A: $1
    function getState : Integer; cdecl;                                         // ()I A: $1
    function isDiscovering : boolean; cdecl;                                    // ()Z A: $1
    function isEnabled : boolean; cdecl;                                        // ()Z A: $1
    function listenUsingInsecureRfcommWithServiceRecord(&name : JString; uuid : JUUID) : JBluetoothServerSocket; cdecl;// (Ljava/lang/String;Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket; A: $1
    function listenUsingRfcommWithServiceRecord(&name : JString; uuid : JUUID) : JBluetoothServerSocket; cdecl;// (Ljava/lang/String;Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket; A: $1
    function setName(&name : JString) : boolean; cdecl;                         // (Ljava/lang/String;)Z A: $1
    function startDiscovery : boolean; cdecl;                                   // ()Z A: $1
    procedure closeProfileProxy(profile : Integer; proxy : JBluetoothProfile) ; cdecl;// (ILandroid/bluetooth/BluetoothProfile;)V A: $1
  end;

  TJBluetoothAdapter = class(TJavaGenericImport<JBluetoothAdapterClass, JBluetoothAdapter>)
  end;

const
  TJBluetoothAdapterERROR = -2147483648;
  TJBluetoothAdapterACTION_STATE_CHANGED = 'android.bluetooth.adapter.action.STATE_CHANGED';
  TJBluetoothAdapterEXTRA_STATE = 'android.bluetooth.adapter.extra.STATE';
  TJBluetoothAdapterEXTRA_PREVIOUS_STATE = 'android.bluetooth.adapter.extra.PREVIOUS_STATE';
  TJBluetoothAdapterSTATE_OFF = 10;
  TJBluetoothAdapterSTATE_TURNING_ON = 11;
  TJBluetoothAdapterSTATE_ON = 12;
  TJBluetoothAdapterSTATE_TURNING_OFF = 13;
  TJBluetoothAdapterACTION_REQUEST_DISCOVERABLE = 'android.bluetooth.adapter.action.REQUEST_DISCOVERABLE';
  TJBluetoothAdapterEXTRA_DISCOVERABLE_DURATION = 'android.bluetooth.adapter.extra.DISCOVERABLE_DURATION';
  TJBluetoothAdapterACTION_REQUEST_ENABLE = 'android.bluetooth.adapter.action.REQUEST_ENABLE';
  TJBluetoothAdapterACTION_SCAN_MODE_CHANGED = 'android.bluetooth.adapter.action.SCAN_MODE_CHANGED';
  TJBluetoothAdapterEXTRA_SCAN_MODE = 'android.bluetooth.adapter.extra.SCAN_MODE';
  TJBluetoothAdapterEXTRA_PREVIOUS_SCAN_MODE = 'android.bluetooth.adapter.extra.PREVIOUS_SCAN_MODE';
  TJBluetoothAdapterSCAN_MODE_NONE = 20;
  TJBluetoothAdapterSCAN_MODE_CONNECTABLE = 21;
  TJBluetoothAdapterSCAN_MODE_CONNECTABLE_DISCOVERABLE = 23;
  TJBluetoothAdapterACTION_DISCOVERY_STARTED = 'android.bluetooth.adapter.action.DISCOVERY_STARTED';
  TJBluetoothAdapterACTION_DISCOVERY_FINISHED = 'android.bluetooth.adapter.action.DISCOVERY_FINISHED';
  TJBluetoothAdapterACTION_LOCAL_NAME_CHANGED = 'android.bluetooth.adapter.action.LOCAL_NAME_CHANGED';
  TJBluetoothAdapterEXTRA_LOCAL_NAME = 'android.bluetooth.adapter.extra.LOCAL_NAME';
  TJBluetoothAdapterACTION_CONNECTION_STATE_CHANGED = 'android.bluetooth.adapter.action.CONNECTION_STATE_CHANGED';
  TJBluetoothAdapterEXTRA_CONNECTION_STATE = 'android.bluetooth.adapter.extra.CONNECTION_STATE';
  TJBluetoothAdapterEXTRA_PREVIOUS_CONNECTION_STATE = 'android.bluetooth.adapter.extra.PREVIOUS_CONNECTION_STATE';
  TJBluetoothAdapterSTATE_DISCONNECTED = 0;
  TJBluetoothAdapterSTATE_CONNECTING = 1;
  TJBluetoothAdapterSTATE_CONNECTED = 2;
  TJBluetoothAdapterSTATE_DISCONNECTING = 3;

implementation

end.
