//
// Generated by JavaToPas v1.4 20140515 - 181808
////////////////////////////////////////////////////////////////////////////////
unit android.database.sqlite.SQLiteStatement;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os;

type
  JSQLiteStatement = interface;

  JSQLiteStatementClass = interface(JObjectClass)
    ['{F96386C8-73CA-4C8D-80F3-15E2652D0269}']
    function executeInsert : Int64; cdecl;                                      // ()J A: $1
    function executeUpdateDelete : Integer; cdecl;                              // ()I A: $1
    function simpleQueryForBlobFileDescriptor : JParcelFileDescriptor; cdecl;   // ()Landroid/os/ParcelFileDescriptor; A: $1
    function simpleQueryForLong : Int64; cdecl;                                 // ()J A: $1
    function simpleQueryForString : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure execute ; cdecl;                                                  // ()V A: $1
  end;

  [JavaSignature('android/database/sqlite/SQLiteStatement')]
  JSQLiteStatement = interface(JObject)
    ['{6CADE4DA-73BF-4150-B7F8-92BBE005A927}']
    function executeInsert : Int64; cdecl;                                      // ()J A: $1
    function executeUpdateDelete : Integer; cdecl;                              // ()I A: $1
    function simpleQueryForBlobFileDescriptor : JParcelFileDescriptor; cdecl;   // ()Landroid/os/ParcelFileDescriptor; A: $1
    function simpleQueryForLong : Int64; cdecl;                                 // ()J A: $1
    function simpleQueryForString : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure execute ; cdecl;                                                  // ()V A: $1
  end;

  TJSQLiteStatement = class(TJavaGenericImport<JSQLiteStatementClass, JSQLiteStatement>)
  end;

implementation

end.
