//
// Generated by JavaToPas v1.4 20140515 - 181517
////////////////////////////////////////////////////////////////////////////////
unit java.util.concurrent.RejectedExecutionException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JRejectedExecutionException = interface;

  JRejectedExecutionExceptionClass = interface(JObjectClass)
    ['{72274C96-355B-40FA-9708-545988B19A8B}']
    function init : JRejectedExecutionException; cdecl; overload;               // ()V A: $1
    function init(&message : JString) : JRejectedExecutionException; cdecl; overload;// (Ljava/lang/String;)V A: $1
    function init(&message : JString; cause : JThrowable) : JRejectedExecutionException; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Throwable;)V A: $1
    function init(cause : JThrowable) : JRejectedExecutionException; cdecl; overload;// (Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('java/util/concurrent/RejectedExecutionException')]
  JRejectedExecutionException = interface(JObject)
    ['{C9B3F48D-32F4-49E4-A0CA-B89853D7A6E1}']
  end;

  TJRejectedExecutionException = class(TJavaGenericImport<JRejectedExecutionExceptionClass, JRejectedExecutionException>)
  end;

implementation

end.
