//
// Generated by JavaToPas v1.4 20140515 - 181545
////////////////////////////////////////////////////////////////////////////////
unit java.lang.Iterable;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JIterable = interface;

  JIterableClass = interface(JObjectClass)
    ['{81C40BB0-74EE-4C51-B462-82D4C67C52C9}']
    function iterator : JIterator; cdecl;                                       // ()Ljava/util/Iterator; A: $401
  end;

  [JavaSignature('java/lang/Iterable')]
  JIterable = interface(JObject)
    ['{2A9ACDB3-8552-4B78-9BCA-4E61B91FD980}']
    function iterator : JIterator; cdecl;                                       // ()Ljava/util/Iterator; A: $401
  end;

  TJIterable = class(TJavaGenericImport<JIterableClass, JIterable>)
  end;

implementation

end.
