//
// Generated by JavaToPas v1.5 20171018 - 170955
////////////////////////////////////////////////////////////////////////////////
unit android.renderscript.Script_InvokeID;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JScript_InvokeID = interface;

  JScript_InvokeIDClass = interface(JObjectClass)
    ['{DD92D976-DE92-4D74-A78F-38808CC78F32}']
  end;

  [JavaSignature('android/renderscript/Script_InvokeID')]
  JScript_InvokeID = interface(JObject)
    ['{113BF51A-0977-4E60-A7EF-CCE04F85B4F5}']
  end;

  TJScript_InvokeID = class(TJavaGenericImport<JScript_InvokeIDClass, JScript_InvokeID>)
  end;

implementation

end.
