//
// Generated by JavaToPas v1.5 20171018 - 170928
////////////////////////////////////////////////////////////////////////////////
unit android.print.PrintDocumentAdapter_LayoutResultCallback;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.print.PrintDocumentInfo;

type
  JPrintDocumentAdapter_LayoutResultCallback = interface;

  JPrintDocumentAdapter_LayoutResultCallbackClass = interface(JObjectClass)
    ['{ACF3E3DA-7912-4558-B2CD-7ED96EA27AB1}']
    procedure onLayoutCancelled ; cdecl;                                        // ()V A: $1
    procedure onLayoutFailed(error : JCharSequence) ; cdecl;                    // (Ljava/lang/CharSequence;)V A: $1
    procedure onLayoutFinished(info : JPrintDocumentInfo; changed : boolean) ; cdecl;// (Landroid/print/PrintDocumentInfo;Z)V A: $1
  end;

  [JavaSignature('android/print/PrintDocumentAdapter_LayoutResultCallback')]
  JPrintDocumentAdapter_LayoutResultCallback = interface(JObject)
    ['{1A10E9DA-E9EB-4951-BF26-1DA48B11A5B0}']
    procedure onLayoutCancelled ; cdecl;                                        // ()V A: $1
    procedure onLayoutFailed(error : JCharSequence) ; cdecl;                    // (Ljava/lang/CharSequence;)V A: $1
    procedure onLayoutFinished(info : JPrintDocumentInfo; changed : boolean) ; cdecl;// (Landroid/print/PrintDocumentInfo;Z)V A: $1
  end;

  TJPrintDocumentAdapter_LayoutResultCallback = class(TJavaGenericImport<JPrintDocumentAdapter_LayoutResultCallbackClass, JPrintDocumentAdapter_LayoutResultCallback>)
  end;

implementation

end.
