//
// Generated by JavaToPas v1.5 20171018 - 170943
////////////////////////////////////////////////////////////////////////////////
unit android.media.AudioTrack_Builder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.media.AudioAttributes,
  android.media.AudioFormat,
  android.media.AudioTrack;

type
  JAudioTrack_Builder = interface;

  JAudioTrack_BuilderClass = interface(JObjectClass)
    ['{3524817B-8A01-4752-A5DF-1552AF14F4EC}']
    function build : JAudioTrack; cdecl;                                        // ()Landroid/media/AudioTrack; A: $1
    function init : JAudioTrack_Builder; cdecl;                                 // ()V A: $1
    function setAudioAttributes(attributes : JAudioAttributes) : JAudioTrack_Builder; cdecl;// (Landroid/media/AudioAttributes;)Landroid/media/AudioTrack$Builder; A: $1
    function setAudioFormat(format : JAudioFormat) : JAudioTrack_Builder; cdecl;// (Landroid/media/AudioFormat;)Landroid/media/AudioTrack$Builder; A: $1
    function setBufferSizeInBytes(bufferSizeInBytes : Integer) : JAudioTrack_Builder; cdecl;// (I)Landroid/media/AudioTrack$Builder; A: $1
    function setSessionId(sessionId : Integer) : JAudioTrack_Builder; cdecl;    // (I)Landroid/media/AudioTrack$Builder; A: $1
    function setTransferMode(mode : Integer) : JAudioTrack_Builder; cdecl;      // (I)Landroid/media/AudioTrack$Builder; A: $1
  end;

  [JavaSignature('android/media/AudioTrack_Builder')]
  JAudioTrack_Builder = interface(JObject)
    ['{9DA71FD0-F38F-4B6B-BD0D-79EC0550E54B}']
    function build : JAudioTrack; cdecl;                                        // ()Landroid/media/AudioTrack; A: $1
    function setAudioAttributes(attributes : JAudioAttributes) : JAudioTrack_Builder; cdecl;// (Landroid/media/AudioAttributes;)Landroid/media/AudioTrack$Builder; A: $1
    function setAudioFormat(format : JAudioFormat) : JAudioTrack_Builder; cdecl;// (Landroid/media/AudioFormat;)Landroid/media/AudioTrack$Builder; A: $1
    function setBufferSizeInBytes(bufferSizeInBytes : Integer) : JAudioTrack_Builder; cdecl;// (I)Landroid/media/AudioTrack$Builder; A: $1
    function setSessionId(sessionId : Integer) : JAudioTrack_Builder; cdecl;    // (I)Landroid/media/AudioTrack$Builder; A: $1
    function setTransferMode(mode : Integer) : JAudioTrack_Builder; cdecl;      // (I)Landroid/media/AudioTrack$Builder; A: $1
  end;

  TJAudioTrack_Builder = class(TJavaGenericImport<JAudioTrack_BuilderClass, JAudioTrack_Builder>)
  end;

implementation

end.
