//
// Generated by JavaToPas v1.5 20171018 - 170916
////////////////////////////////////////////////////////////////////////////////
unit android.text.style.LineHeightSpan_WithDensity;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.graphics.Paint_FontMetricsInt,
  android.text.TextPaint;

type
  JLineHeightSpan_WithDensity = interface;

  JLineHeightSpan_WithDensityClass = interface(JObjectClass)
    ['{B5B41951-DA03-48ED-9063-C62C53FC2D57}']
    procedure chooseHeight(JCharSequenceparam0 : JCharSequence; Integerparam1 : Integer; Integerparam2 : Integer; Integerparam3 : Integer; Integerparam4 : Integer; JPaint_FontMetricsIntparam5 : JPaint_FontMetricsInt; JTextPaintparam6 : JTextPaint) ; cdecl;// (Ljava/lang/CharSequence;IIIILandroid/graphics/Paint$FontMetricsInt;Landroid/text/TextPaint;)V A: $401
  end;

  [JavaSignature('android/text/style/LineHeightSpan_WithDensity')]
  JLineHeightSpan_WithDensity = interface(JObject)
    ['{1EE1FBEA-C324-41BC-A7AB-D1E2E5B971FB}']
    procedure chooseHeight(JCharSequenceparam0 : JCharSequence; Integerparam1 : Integer; Integerparam2 : Integer; Integerparam3 : Integer; Integerparam4 : Integer; JPaint_FontMetricsIntparam5 : JPaint_FontMetricsInt; JTextPaintparam6 : JTextPaint) ; cdecl;// (Ljava/lang/CharSequence;IIIILandroid/graphics/Paint$FontMetricsInt;Landroid/text/TextPaint;)V A: $401
  end;

  TJLineHeightSpan_WithDensity = class(TJavaGenericImport<JLineHeightSpan_WithDensityClass, JLineHeightSpan_WithDensity>)
  end;

implementation

end.
