//
// Generated by JavaToPas v1.5 20171018 - 171003
////////////////////////////////////////////////////////////////////////////////
unit android.hardware.display.VirtualDisplay;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.view.Display,
  android.view.Surface;

type
  JVirtualDisplay = interface;

  JVirtualDisplayClass = interface(JObjectClass)
    ['{ED4C66B9-3341-4FE3-B19A-528242A9BE8F}']
    function getDisplay : JDisplay; cdecl;                                      // ()Landroid/view/Display; A: $1
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure release ; cdecl;                                                  // ()V A: $1
    procedure resize(width : Integer; height : Integer; densityDpi : Integer) ; cdecl;// (III)V A: $1
    procedure setSurface(surface : JSurface) ; cdecl;                           // (Landroid/view/Surface;)V A: $1
  end;

  [JavaSignature('android/hardware/display/VirtualDisplay$Callback')]
  JVirtualDisplay = interface(JObject)
    ['{DFC290A8-0152-4486-94F8-8790B6D9E89B}']
    function getDisplay : JDisplay; cdecl;                                      // ()Landroid/view/Display; A: $1
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure release ; cdecl;                                                  // ()V A: $1
    procedure resize(width : Integer; height : Integer; densityDpi : Integer) ; cdecl;// (III)V A: $1
    procedure setSurface(surface : JSurface) ; cdecl;                           // (Landroid/view/Surface;)V A: $1
  end;

  TJVirtualDisplay = class(TJavaGenericImport<JVirtualDisplayClass, JVirtualDisplay>)
  end;

implementation

end.
