//
// Generated by JavaToPas v1.5 20180804 - 083042
////////////////////////////////////////////////////////////////////////////////
unit android.media.audiofx.LoudnessEnhancer;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JLoudnessEnhancer = interface;

  JLoudnessEnhancerClass = interface(JObjectClass)
    ['{92AE403F-E7EF-41F1-AA91-AED845BE8749}']
    function _GetPARAM_TARGET_GAIN_MB : Integer; cdecl;                         //  A: $19
    function getTargetGain : Single; cdecl;                                     // ()F A: $1
    function init(audioSession : Integer) : JLoudnessEnhancer; cdecl;           // (I)V A: $1
    procedure setTargetGain(gainmB : Integer) ; cdecl;                          // (I)V A: $1
    property PARAM_TARGET_GAIN_MB : Integer read _GetPARAM_TARGET_GAIN_MB;      // I A: $19
  end;

  [JavaSignature('android/media/audiofx/LoudnessEnhancer')]
  JLoudnessEnhancer = interface(JObject)
    ['{A8161CE8-F490-45CD-BA0B-3A7CAA0DB9FE}']
    function getTargetGain : Single; cdecl;                                     // ()F A: $1
    procedure setTargetGain(gainmB : Integer) ; cdecl;                          // (I)V A: $1
  end;

  TJLoudnessEnhancer = class(TJavaGenericImport<JLoudnessEnhancerClass, JLoudnessEnhancer>)
  end;

const
  TJLoudnessEnhancerPARAM_TARGET_GAIN_MB = 0;

implementation

end.
