//
// Generated by JavaToPas v1.5 20180804 - 083154
////////////////////////////////////////////////////////////////////////////////
unit android.security.keystore.UserNotAuthenticatedException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JUserNotAuthenticatedException = interface;

  JUserNotAuthenticatedExceptionClass = interface(JObjectClass)
    ['{2799C77E-5B43-47AE-9F47-6FB2EA3524AA}']
    function init : JUserNotAuthenticatedException; cdecl; overload;            // ()V A: $1
    function init(&message : JString) : JUserNotAuthenticatedException; cdecl; overload;// (Ljava/lang/String;)V A: $1
    function init(&message : JString; cause : JThrowable) : JUserNotAuthenticatedException; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('android/security/keystore/UserNotAuthenticatedException')]
  JUserNotAuthenticatedException = interface(JObject)
    ['{C365008E-5B69-4E73-BE8E-F85C438D343C}']
  end;

  TJUserNotAuthenticatedException = class(TJavaGenericImport<JUserNotAuthenticatedExceptionClass, JUserNotAuthenticatedException>)
  end;

implementation

end.
