//
// Generated by JavaToPas v1.5 20180804 - 083055
////////////////////////////////////////////////////////////////////////////////
unit android.service.autofill.LuhnChecksumValidator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os,
  android.view.autofill.AutofillId;

type
  JLuhnChecksumValidator = interface;

  JLuhnChecksumValidatorClass = interface(JObjectClass)
    ['{F3E6922C-919C-498B-BB74-FEF1EA470F94}']
    function _GetCREATOR : JParcelable_Creator; cdecl;                          //  A: $19
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function init(ids : TJavaArray<JAutofillId>) : JLuhnChecksumValidator; cdecl;// ([Landroid/view/autofill/AutofillId;)V A: $81
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(parcel : JParcel; flags : Integer) ; cdecl;         // (Landroid/os/Parcel;I)V A: $1
    property CREATOR : JParcelable_Creator read _GetCREATOR;                    // Landroid/os/Parcelable$Creator; A: $19
  end;

  [JavaSignature('android/service/autofill/LuhnChecksumValidator')]
  JLuhnChecksumValidator = interface(JObject)
    ['{6DE702CE-2571-47E3-97B3-B2BC45FD4C1C}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(parcel : JParcel; flags : Integer) ; cdecl;         // (Landroid/os/Parcel;I)V A: $1
  end;

  TJLuhnChecksumValidator = class(TJavaGenericImport<JLuhnChecksumValidatorClass, JLuhnChecksumValidator>)
  end;

implementation

end.
