//
// Generated by JavaToPas v1.5 20180804 - 083242
////////////////////////////////////////////////////////////////////////////////
unit java.security.Permission;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JPermissionCollection = interface; // merged
  JPermission = interface;

  JPermissionClass = interface(JObjectClass)
    ['{964DF246-2A8A-4ED0-AB20-43D1045D6C6A}']
    function getActions : JString; cdecl;                                       // ()Ljava/lang/String; A: $401
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $11
    function implies(JPermissionparam0 : JPermission) : boolean; cdecl;         // (Ljava/security/Permission;)Z A: $401
    function init(&name : JString) : JPermission; cdecl;                        // (Ljava/lang/String;)V A: $1
    function newPermissionCollection : JPermissionCollection; cdecl;            // ()Ljava/security/PermissionCollection; A: $1
    procedure checkGuard(&object : JObject) ; cdecl;                            // (Ljava/lang/Object;)V A: $1
  end;

  [JavaSignature('java/security/Permission')]
  JPermission = interface(JObject)
    ['{C3E7128A-ECFC-4161-87A3-50F7757B10A7}']
    function getActions : JString; cdecl;                                       // ()Ljava/lang/String; A: $401
    function implies(JPermissionparam0 : JPermission) : boolean; cdecl;         // (Ljava/security/Permission;)Z A: $401
    function newPermissionCollection : JPermissionCollection; cdecl;            // ()Ljava/security/PermissionCollection; A: $1
    procedure checkGuard(&object : JObject) ; cdecl;                            // (Ljava/lang/Object;)V A: $1
  end;

  TJPermission = class(TJavaGenericImport<JPermissionClass, JPermission>)
  end;

  // Merged from: .\java.security.PermissionCollection.pas
  JPermissionCollectionClass = interface(JObjectClass)
    ['{9038990F-E863-4D23-8CD1-6627BE750C38}']
    function elements : JEnumeration; cdecl;                                    // ()Ljava/util/Enumeration; A: $401
    function implies(JPermissionparam0 : JPermission) : boolean; cdecl;         // (Ljava/security/Permission;)Z A: $401
    function init : JPermissionCollection; cdecl;                               // ()V A: $1
    function isReadOnly : boolean; cdecl;                                       // ()Z A: $1
    procedure add(JPermissionparam0 : JPermission) ; cdecl;                     // (Ljava/security/Permission;)V A: $401
    procedure setReadOnly ; cdecl;                                              // ()V A: $1
  end;

  [JavaSignature('java/security/PermissionCollection')]
  JPermissionCollection = interface(JObject)
    ['{413BE0C8-C917-4042-A4CE-FC0AD3B63EBA}']
    function elements : JEnumeration; cdecl;                                    // ()Ljava/util/Enumeration; A: $401
    function implies(JPermissionparam0 : JPermission) : boolean; cdecl;         // (Ljava/security/Permission;)Z A: $401
    function isReadOnly : boolean; cdecl;                                       // ()Z A: $1
    procedure add(JPermissionparam0 : JPermission) ; cdecl;                     // (Ljava/security/Permission;)V A: $401
    procedure setReadOnly ; cdecl;                                              // ()V A: $1
  end;

  TJPermissionCollection = class(TJavaGenericImport<JPermissionCollectionClass, JPermissionCollection>)
  end;


implementation

end.
