//
// Generated by JavaToPas v1.5 20171018 - 171336
////////////////////////////////////////////////////////////////////////////////
unit android.media.MediaCas_PluginDescriptor;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JMediaCas_PluginDescriptor = interface;

  JMediaCas_PluginDescriptorClass = interface(JObjectClass)
    ['{AF625018-9109-4F14-AAF7-85A667CFEA96}']
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getSystemId : Integer; cdecl;                                      // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('android/media/MediaCas_PluginDescriptor')]
  JMediaCas_PluginDescriptor = interface(JObject)
    ['{95BD7731-BFFF-4DD4-BD8E-0C5A4741F8F8}']
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getSystemId : Integer; cdecl;                                      // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJMediaCas_PluginDescriptor = class(TJavaGenericImport<JMediaCas_PluginDescriptorClass, JMediaCas_PluginDescriptor>)
  end;

implementation

end.
