//
// Generated by JavaToPas v1.5 20171018 - 171344
////////////////////////////////////////////////////////////////////////////////
unit android.net.wifi.p2p.nsd.WifiP2pDnsSdServiceInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWifiP2pDnsSdServiceInfo = interface;

  JWifiP2pDnsSdServiceInfoClass = interface(JObjectClass)
    ['{EC2D841A-996D-4F7D-85DE-BCA045B18B88}']
    function newInstance(instanceName : JString; serviceType : JString; txtMap : JMap) : JWifiP2pDnsSdServiceInfo; cdecl;// (Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)Landroid/net/wifi/p2p/nsd/WifiP2pDnsSdServiceInfo; A: $9
  end;

  [JavaSignature('android/net/wifi/p2p/nsd/WifiP2pDnsSdServiceInfo')]
  JWifiP2pDnsSdServiceInfo = interface(JObject)
    ['{BC21DF86-A5B0-45E7-B3C3-2CBEDD67DEE5}']
  end;

  TJWifiP2pDnsSdServiceInfo = class(TJavaGenericImport<JWifiP2pDnsSdServiceInfoClass, JWifiP2pDnsSdServiceInfo>)
  end;

implementation

end.
