//
// Generated by JavaToPas v1.5 20171018 - 171311
////////////////////////////////////////////////////////////////////////////////
unit android.graphics.Paint_Align;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JPaint_Align = interface;

  JPaint_AlignClass = interface(JObjectClass)
    ['{B49272BB-6F43-4EF0-BD4C-DF1DC3B96A5A}']
    function _GetCENTER : JPaint_Align; cdecl;                                  //  A: $4019
    function _GetLEFT : JPaint_Align; cdecl;                                    //  A: $4019
    function _GetRIGHT : JPaint_Align; cdecl;                                   //  A: $4019
    function valueOf(&name : JString) : JPaint_Align; cdecl;                    // (Ljava/lang/String;)Landroid/graphics/Paint$Align; A: $9
    function values : TJavaArray<JPaint_Align>; cdecl;                          // ()[Landroid/graphics/Paint$Align; A: $9
    property CENTER : JPaint_Align read _GetCENTER;                             // Landroid/graphics/Paint$Align; A: $4019
    property LEFT : JPaint_Align read _GetLEFT;                                 // Landroid/graphics/Paint$Align; A: $4019
    property RIGHT : JPaint_Align read _GetRIGHT;                               // Landroid/graphics/Paint$Align; A: $4019
  end;

  [JavaSignature('android/graphics/Paint_Align')]
  JPaint_Align = interface(JObject)
    ['{51CF8EBE-F5B0-4AE3-8716-7D58EA9D9AEA}']
  end;

  TJPaint_Align = class(TJavaGenericImport<JPaint_AlignClass, JPaint_Align>)
  end;

implementation

end.
