//
// Generated by JavaToPas v1.5 20171018 - 171140
////////////////////////////////////////////////////////////////////////////////
unit javax.microedition.khronos.egl.EGLConfig;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEGLConfig = interface;

  JEGLConfigClass = interface(JObjectClass)
    ['{0566EC12-8EE4-4FCB-9BE7-84C7FDCA7E62}']
    function init : JEGLConfig; cdecl;                                          // ()V A: $1
  end;

  [JavaSignature('javax/microedition/khronos/egl/EGLConfig')]
  JEGLConfig = interface(JObject)
    ['{010B9AEE-C23C-44B6-8EB5-2D6ECABE8B26}']
  end;

  TJEGLConfig = class(TJavaGenericImport<JEGLConfigClass, JEGLConfig>)
  end;

implementation

end.
