//
// Generated by JavaToPas v1.4 20140515 - 181306
////////////////////////////////////////////////////////////////////////////////
unit android.graphics.Rasterizer;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JRasterizer = interface;

  JRasterizerClass = interface(JObjectClass)
    ['{D862CC5A-D4F4-4135-B2AD-670B9F62B011}']
    function init : JRasterizer; cdecl;                                         // ()V A: $1
  end;

  [JavaSignature('android/graphics/Rasterizer')]
  JRasterizer = interface(JObject)
    ['{1AE4A194-B131-47E2-9772-7FC5A5EEFE74}']
  end;

  TJRasterizer = class(TJavaGenericImport<JRasterizerClass, JRasterizer>)
  end;

implementation

end.
