//
// Generated by JavaToPas v1.4 20140515 - 181342
////////////////////////////////////////////////////////////////////////////////
unit android.test.mock.MockDialogInterface;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JMockDialogInterface = interface;

  JMockDialogInterfaceClass = interface(JObjectClass)
    ['{838A6937-57B9-4079-BBD4-D3AEDAD7B551}']
    function init : JMockDialogInterface; cdecl;                                // ()V A: $1
    procedure cancel ; cdecl;                                                   // ()V A: $1
    procedure dismiss ; cdecl;                                                  // ()V A: $1
  end;

  [JavaSignature('android/test/mock/MockDialogInterface')]
  JMockDialogInterface = interface(JObject)
    ['{5BD994CB-3E68-4743-ABC2-CF4113D17B5D}']
    procedure cancel ; cdecl;                                                   // ()V A: $1
    procedure dismiss ; cdecl;                                                  // ()V A: $1
  end;

  TJMockDialogInterface = class(TJavaGenericImport<JMockDialogInterfaceClass, JMockDialogInterface>)
  end;

implementation

end.
