//
// Generated by JavaToPas v1.4 20140515 - 181030
////////////////////////////////////////////////////////////////////////////////
unit android.database.CursorIndexOutOfBoundsException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JCursorIndexOutOfBoundsException = interface;

  JCursorIndexOutOfBoundsExceptionClass = interface(JObjectClass)
    ['{EEB7214F-D34D-4FB5-BE0B-DC2F98CE2295}']
    function init(&index : Integer; size : Integer) : JCursorIndexOutOfBoundsException; cdecl; overload;// (II)V A: $1
    function init(&message : JString) : JCursorIndexOutOfBoundsException; cdecl; overload;// (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('android/database/CursorIndexOutOfBoundsException')]
  JCursorIndexOutOfBoundsException = interface(JObject)
    ['{00920B4A-D646-4AC3-9763-DA6F668A0586}']
  end;

  TJCursorIndexOutOfBoundsException = class(TJavaGenericImport<JCursorIndexOutOfBoundsExceptionClass, JCursorIndexOutOfBoundsException>)
  end;

implementation

end.
