//
// Generated by JavaToPas v1.4 20140515 - 181454
////////////////////////////////////////////////////////////////////////////////
unit android.R_animator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_animator = interface;

  JR_animatorClass = interface(JObjectClass)
    ['{BD5BE4D7-A12D-421E-932D-2A755E2DD2D7}']
    function _Getfade_in : Integer; cdecl;                                      //  A: $19
    function _Getfade_out : Integer; cdecl;                                     //  A: $19
    function init : JR_animator; cdecl;                                         // ()V A: $1
    property fade_in : Integer read _Getfade_in;                                // I A: $19
    property fade_out : Integer read _Getfade_out;                              // I A: $19
  end;

  [JavaSignature('android/R_animator')]
  JR_animator = interface(JObject)
    ['{F97890BC-02CC-4139-A93D-553CA33A13E9}']
  end;

  TJR_animator = class(TJavaGenericImport<JR_animatorClass, JR_animator>)
  end;

const
  TJR_animatorfade_in = 17498112;
  TJR_animatorfade_out = 17498113;

implementation

end.
