//
// Generated by JavaToPas v1.4 20140515 - 181021
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.conn.ClientConnectionManagerFactory;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.apache.http.conn.ClientConnectionManager,
  org.apache.http.params.HttpParams,
  org.apache.http.conn.scheme.SchemeRegistry;

type
  JClientConnectionManagerFactory = interface;

  JClientConnectionManagerFactoryClass = interface(JObjectClass)
    ['{B6E96ED0-3A2C-4C06-9DAB-DAE8048F83C3}']
    function newInstance(JHttpParamsparam0 : JHttpParams; JSchemeRegistryparam1 : JSchemeRegistry) : JClientConnectionManager; cdecl;// (Lorg/apache/http/params/HttpParams;Lorg/apache/http/conn/scheme/SchemeRegistry;)Lorg/apache/http/conn/ClientConnectionManager; A: $401
  end;

  [JavaSignature('org/apache/http/conn/ClientConnectionManagerFactory')]
  JClientConnectionManagerFactory = interface(JObject)
    ['{23C09FC8-34C1-4EA9-AB8C-82FF54B3D24D}']
    function newInstance(JHttpParamsparam0 : JHttpParams; JSchemeRegistryparam1 : JSchemeRegistry) : JClientConnectionManager; cdecl;// (Lorg/apache/http/params/HttpParams;Lorg/apache/http/conn/scheme/SchemeRegistry;)Lorg/apache/http/conn/ClientConnectionManager; A: $401
  end;

  TJClientConnectionManagerFactory = class(TJavaGenericImport<JClientConnectionManagerFactoryClass, JClientConnectionManagerFactory>)
  end;

implementation

end.
