//
// Generated by JavaToPas v1.4 20140515 - 180747
////////////////////////////////////////////////////////////////////////////////
unit android.provider.ContactsContract_DataColumnsWithJoins;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JContactsContract_DataColumnsWithJoins = interface;

  JContactsContract_DataColumnsWithJoinsClass = interface(JObjectClass)
    ['{E0B50C82-8FB5-4239-87E8-3AF7713F2CF8}']
  end;

  [JavaSignature('android/provider/ContactsContract_DataColumnsWithJoins')]
  JContactsContract_DataColumnsWithJoins = interface(JObject)
    ['{07AA30EF-385E-4622-A470-B2065E770C64}']
  end;

  TJContactsContract_DataColumnsWithJoins = class(TJavaGenericImport<JContactsContract_DataColumnsWithJoinsClass, JContactsContract_DataColumnsWithJoins>)
  end;

implementation

end.
