//
// Generated by JavaToPas v1.4 20140515 - 180822
////////////////////////////////////////////////////////////////////////////////
unit javax.crypto.NoSuchPaddingException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JNoSuchPaddingException = interface;

  JNoSuchPaddingExceptionClass = interface(JObjectClass)
    ['{2520D84C-D25F-4BD3-AF22-62E9CD90BFE8}']
    function init : JNoSuchPaddingException; cdecl; overload;                   // ()V A: $1
    function init(msg : JString) : JNoSuchPaddingException; cdecl; overload;    // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('javax/crypto/NoSuchPaddingException')]
  JNoSuchPaddingException = interface(JObject)
    ['{A902EA6A-9079-494E-B20B-5FED29C678FF}']
  end;

  TJNoSuchPaddingException = class(TJavaGenericImport<JNoSuchPaddingExceptionClass, JNoSuchPaddingException>)
  end;

implementation

end.
