//
// Generated by JavaToPas v1.4 20140515 - 180822
////////////////////////////////////////////////////////////////////////////////
unit javax.sql.RowSetReader;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  javax.sql.RowSetInternal;

type
  JRowSetReader = interface;

  JRowSetReaderClass = interface(JObjectClass)
    ['{416D489C-0DDD-4E31-870F-66F0CD95262B}']
    procedure readData(JRowSetInternalparam0 : JRowSetInternal) ; cdecl;        // (Ljavax/sql/RowSetInternal;)V A: $401
  end;

  [JavaSignature('javax/sql/RowSetReader')]
  JRowSetReader = interface(JObject)
    ['{840B9CCC-7D9F-426D-8D17-66D8FB6F42B5}']
    procedure readData(JRowSetInternalparam0 : JRowSetInternal) ; cdecl;        // (Ljavax/sql/RowSetInternal;)V A: $401
  end;

  TJRowSetReader = class(TJavaGenericImport<JRowSetReaderClass, JRowSetReader>)
  end;

implementation

end.
