//
// Generated by JavaToPas v1.4 20140515 - 180659
////////////////////////////////////////////////////////////////////////////////
unit org.w3c.dom.Comment;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JComment = interface;

  JCommentClass = interface(JObjectClass)
    ['{2DD9D502-6340-4164-ABB1-9EF16E30D663}']
  end;

  [JavaSignature('org/w3c/dom/Comment')]
  JComment = interface(JObject)
    ['{725155A5-736D-4640-97A2-D90E3C2E0FE7}']
  end;

  TJComment = class(TJavaGenericImport<JCommentClass, JComment>)
  end;

implementation

end.
