//
// Generated by JavaToPas v1.5 20150830 - 103134
////////////////////////////////////////////////////////////////////////////////
unit android.text.style.LeadingMarginSpan_LeadingMarginSpan2;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JLeadingMarginSpan_LeadingMarginSpan2 = interface;

  JLeadingMarginSpan_LeadingMarginSpan2Class = interface(JObjectClass)
    ['{372CA4DB-7BF5-4AC5-8C3D-1ED798B495F3}']
    function getLeadingMarginLineCount : Integer; cdecl;                        // ()I A: $401
  end;

  [JavaSignature('android/text/style/LeadingMarginSpan_LeadingMarginSpan2')]
  JLeadingMarginSpan_LeadingMarginSpan2 = interface(JObject)
    ['{FA1B16D9-6055-4E9C-A2AB-6A53BAAF5066}']
    function getLeadingMarginLineCount : Integer; cdecl;                        // ()I A: $401
  end;

  TJLeadingMarginSpan_LeadingMarginSpan2 = class(TJavaGenericImport<JLeadingMarginSpan_LeadingMarginSpan2Class, JLeadingMarginSpan_LeadingMarginSpan2>)
  end;

implementation

end.
