//
// Generated by JavaToPas v1.5 20150830 - 103202
////////////////////////////////////////////////////////////////////////////////
unit android.view.SurfaceHolder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.graphics.Bitmap,
  android.graphics.Rect,
  android.view.Surface;

type
  JSurfaceHolder_Callback = interface; // merged
  JSurfaceHolder = interface;

  JSurfaceHolderClass = interface(JObjectClass)
    ['{B46F5D1C-126B-4ACE-A121-65FC10CBAE88}']
    function _GetSURFACE_TYPE_GPU : Integer; cdecl;                             //  A: $19
    function _GetSURFACE_TYPE_HARDWARE : Integer; cdecl;                        //  A: $19
    function _GetSURFACE_TYPE_NORMAL : Integer; cdecl;                          //  A: $19
    function _GetSURFACE_TYPE_PUSH_BUFFERS : Integer; cdecl;                    //  A: $19
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $401
    function getSurfaceFrame : JRect; cdecl;                                    // ()Landroid/graphics/Rect; A: $401
    function isCreating : boolean; cdecl;                                       // ()Z A: $401
    function lockCanvas : JCanvas; cdecl; overload;                             // ()Landroid/graphics/Canvas; A: $401
    function lockCanvas(JRectparam0 : JRect) : JCanvas; cdecl; overload;        // (Landroid/graphics/Rect;)Landroid/graphics/Canvas; A: $401
    procedure addCallback(JSurfaceHolder_Callbackparam0 : JSurfaceHolder_Callback) ; cdecl;// (Landroid/view/SurfaceHolder$Callback;)V A: $401
    procedure removeCallback(JSurfaceHolder_Callbackparam0 : JSurfaceHolder_Callback) ; cdecl;// (Landroid/view/SurfaceHolder$Callback;)V A: $401
    procedure setFixedSize(Integerparam0 : Integer; Integerparam1 : Integer) ; cdecl;// (II)V A: $401
    procedure setFormat(Integerparam0 : Integer) ; cdecl;                       // (I)V A: $401
    procedure setKeepScreenOn(booleanparam0 : boolean) ; cdecl;                 // (Z)V A: $401
    procedure setSizeFromLayout ; cdecl;                                        // ()V A: $401
    procedure setType(Integerparam0 : Integer) ; deprecated; cdecl;             // (I)V A: $401
    procedure unlockCanvasAndPost(JCanvasparam0 : JCanvas) ; cdecl;             // (Landroid/graphics/Canvas;)V A: $401
    property SURFACE_TYPE_GPU : Integer read _GetSURFACE_TYPE_GPU;              // I A: $19
    property SURFACE_TYPE_HARDWARE : Integer read _GetSURFACE_TYPE_HARDWARE;    // I A: $19
    property SURFACE_TYPE_NORMAL : Integer read _GetSURFACE_TYPE_NORMAL;        // I A: $19
    property SURFACE_TYPE_PUSH_BUFFERS : Integer read _GetSURFACE_TYPE_PUSH_BUFFERS;// I A: $19
  end;

  [JavaSignature('android/view/SurfaceHolder$Callback2')]
  JSurfaceHolder = interface(JObject)
    ['{538486CA-E4AD-4D6C-88F0-D7D003DDDB9D}']
    function getSurface : JSurface; cdecl;                                      // ()Landroid/view/Surface; A: $401
    function getSurfaceFrame : JRect; cdecl;                                    // ()Landroid/graphics/Rect; A: $401
    function isCreating : boolean; cdecl;                                       // ()Z A: $401
    function lockCanvas : JCanvas; cdecl; overload;                             // ()Landroid/graphics/Canvas; A: $401
    function lockCanvas(JRectparam0 : JRect) : JCanvas; cdecl; overload;        // (Landroid/graphics/Rect;)Landroid/graphics/Canvas; A: $401
    procedure addCallback(JSurfaceHolder_Callbackparam0 : JSurfaceHolder_Callback) ; cdecl;// (Landroid/view/SurfaceHolder$Callback;)V A: $401
    procedure removeCallback(JSurfaceHolder_Callbackparam0 : JSurfaceHolder_Callback) ; cdecl;// (Landroid/view/SurfaceHolder$Callback;)V A: $401
    procedure setFixedSize(Integerparam0 : Integer; Integerparam1 : Integer) ; cdecl;// (II)V A: $401
    procedure setFormat(Integerparam0 : Integer) ; cdecl;                       // (I)V A: $401
    procedure setKeepScreenOn(booleanparam0 : boolean) ; cdecl;                 // (Z)V A: $401
    procedure setSizeFromLayout ; cdecl;                                        // ()V A: $401
    procedure setType(Integerparam0 : Integer) ; deprecated; cdecl;             // (I)V A: $401
    procedure unlockCanvasAndPost(JCanvasparam0 : JCanvas) ; cdecl;             // (Landroid/graphics/Canvas;)V A: $401
  end;

  TJSurfaceHolder = class(TJavaGenericImport<JSurfaceHolderClass, JSurfaceHolder>)
  end;

  // Merged from: .\android.view.SurfaceHolder_Callback.pas
  JSurfaceHolder_CallbackClass = interface(JObjectClass)
    ['{F71EAE88-A61C-49D3-A06F-AA7458D1F46D}']
    procedure surfaceChanged(JSurfaceHolderparam0 : JSurfaceHolder; Integerparam1 : Integer; Integerparam2 : Integer; Integerparam3 : Integer) ; cdecl;// (Landroid/view/SurfaceHolder;III)V A: $401
    procedure surfaceCreated(JSurfaceHolderparam0 : JSurfaceHolder) ; cdecl;    // (Landroid/view/SurfaceHolder;)V A: $401
    procedure surfaceDestroyed(JSurfaceHolderparam0 : JSurfaceHolder) ; cdecl;  // (Landroid/view/SurfaceHolder;)V A: $401
  end;

  [JavaSignature('android/view/SurfaceHolder_Callback')]
  JSurfaceHolder_Callback = interface(JObject)
    ['{E827B1F3-3760-4F5D-A0B9-036C1530AD35}']
    procedure surfaceChanged(JSurfaceHolderparam0 : JSurfaceHolder; Integerparam1 : Integer; Integerparam2 : Integer; Integerparam3 : Integer) ; cdecl;// (Landroid/view/SurfaceHolder;III)V A: $401
    procedure surfaceCreated(JSurfaceHolderparam0 : JSurfaceHolder) ; cdecl;    // (Landroid/view/SurfaceHolder;)V A: $401
    procedure surfaceDestroyed(JSurfaceHolderparam0 : JSurfaceHolder) ; cdecl;  // (Landroid/view/SurfaceHolder;)V A: $401
  end;

  TJSurfaceHolder_Callback = class(TJavaGenericImport<JSurfaceHolder_CallbackClass, JSurfaceHolder_Callback>)
  end;


const
  TJSurfaceHolderSURFACE_TYPE_GPU = 2;
  TJSurfaceHolderSURFACE_TYPE_HARDWARE = 1;
  TJSurfaceHolderSURFACE_TYPE_NORMAL = 0;
  TJSurfaceHolderSURFACE_TYPE_PUSH_BUFFERS = 3;

implementation

end.
