//
// Generated by JavaToPas v1.4 20140515 - 181842
////////////////////////////////////////////////////////////////////////////////
unit java.io.ObjectInputValidation;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JObjectInputValidation = interface;

  JObjectInputValidationClass = interface(JObjectClass)
    ['{484A070D-4C8E-481C-8BEB-1E3F7F541D8B}']
    procedure validateObject ; cdecl;                                           // ()V A: $401
  end;

  [JavaSignature('java/io/ObjectInputValidation')]
  JObjectInputValidation = interface(JObject)
    ['{FF9964D9-45CD-4C3B-AA8A-F3349E5E3B0E}']
    procedure validateObject ; cdecl;                                           // ()V A: $401
  end;

  TJObjectInputValidation = class(TJavaGenericImport<JObjectInputValidationClass, JObjectInputValidation>)
  end;

implementation

end.
