//
// Generated by JavaToPas v1.5 20150831 - 132349
////////////////////////////////////////////////////////////////////////////////
unit android.media.MediaTimestamp;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JMediaTimestamp = interface;

  JMediaTimestampClass = interface(JObjectClass)
    ['{5EAD584F-ACC6-47DC-90F9-3D18E2914BC3}']
    function getAnchorMediaTimeUs : Int64; cdecl;                               // ()J A: $1
    function getAnchorSytemNanoTime : Int64; cdecl;                             // ()J A: $1
    function getMediaClockRate : Single; cdecl;                                 // ()F A: $1
  end;

  [JavaSignature('android/media/MediaTimestamp')]
  JMediaTimestamp = interface(JObject)
    ['{30358298-1EED-4BD4-99DE-C57DC8F34620}']
    function getAnchorMediaTimeUs : Int64; cdecl;                               // ()J A: $1
    function getAnchorSytemNanoTime : Int64; cdecl;                             // ()J A: $1
    function getMediaClockRate : Single; cdecl;                                 // ()F A: $1
  end;

  TJMediaTimestamp = class(TJavaGenericImport<JMediaTimestampClass, JMediaTimestamp>)
  end;

implementation

end.
