//
// Generated by JavaToPas v1.5 20150831 - 132232
////////////////////////////////////////////////////////////////////////////////
unit java.util.concurrent.atomic.AtomicBoolean;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JAtomicBoolean = interface;

  JAtomicBooleanClass = interface(JObjectClass)
    ['{2F8698F3-2EE0-4DB6-AF2B-198A1CA42C6D}']
    function compareAndSet(expect : boolean; update : boolean) : boolean; cdecl;// (ZZ)Z A: $11
    function get : boolean; cdecl;                                              // ()Z A: $11
    function getAndSet(newValue : boolean) : boolean; cdecl;                    // (Z)Z A: $11
    function init : JAtomicBoolean; cdecl; overload;                            // ()V A: $1
    function init(initialValue : boolean) : JAtomicBoolean; cdecl; overload;    // (Z)V A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function weakCompareAndSet(expect : boolean; update : boolean) : boolean; cdecl;// (ZZ)Z A: $1
    procedure &set(newValue : boolean) ; cdecl;                                 // (Z)V A: $11
    procedure lazySet(newValue : boolean) ; cdecl;                              // (Z)V A: $11
  end;

  [JavaSignature('java/util/concurrent/atomic/AtomicBoolean')]
  JAtomicBoolean = interface(JObject)
    ['{7DC7B1E2-3A7C-466F-B6C2-F0B4CDD533F9}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function weakCompareAndSet(expect : boolean; update : boolean) : boolean; cdecl;// (ZZ)Z A: $1
  end;

  TJAtomicBoolean = class(TJavaGenericImport<JAtomicBooleanClass, JAtomicBoolean>)
  end;

implementation

end.
