//
// Generated by JavaToPas v1.5 20180804 - 082552
////////////////////////////////////////////////////////////////////////////////
unit android.media.AudioRecord_Builder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.media.AudioFormat,
  android.media.AudioRecord;

type
  JAudioRecord_Builder = interface;

  JAudioRecord_BuilderClass = interface(JObjectClass)
    ['{F605A09E-F15E-4F41-A165-B617B69A6DAA}']
    function build : JAudioRecord; cdecl;                                       // ()Landroid/media/AudioRecord; A: $1
    function init : JAudioRecord_Builder; cdecl;                                // ()V A: $1
    function setAudioFormat(format : JAudioFormat) : JAudioRecord_Builder; cdecl;// (Landroid/media/AudioFormat;)Landroid/media/AudioRecord$Builder; A: $1
    function setAudioSource(source : Integer) : JAudioRecord_Builder; cdecl;    // (I)Landroid/media/AudioRecord$Builder; A: $1
    function setBufferSizeInBytes(bufferSizeInBytes : Integer) : JAudioRecord_Builder; cdecl;// (I)Landroid/media/AudioRecord$Builder; A: $1
  end;

  [JavaSignature('android/media/AudioRecord_Builder')]
  JAudioRecord_Builder = interface(JObject)
    ['{1A2793BF-DE0C-45F3-864B-DAFFA049A36A}']
    function build : JAudioRecord; cdecl;                                       // ()Landroid/media/AudioRecord; A: $1
    function setAudioFormat(format : JAudioFormat) : JAudioRecord_Builder; cdecl;// (Landroid/media/AudioFormat;)Landroid/media/AudioRecord$Builder; A: $1
    function setAudioSource(source : Integer) : JAudioRecord_Builder; cdecl;    // (I)Landroid/media/AudioRecord$Builder; A: $1
    function setBufferSizeInBytes(bufferSizeInBytes : Integer) : JAudioRecord_Builder; cdecl;// (I)Landroid/media/AudioRecord$Builder; A: $1
  end;

  TJAudioRecord_Builder = class(TJavaGenericImport<JAudioRecord_BuilderClass, JAudioRecord_Builder>)
  end;

implementation

end.
