//
// Generated by JavaToPas v1.5 20180804 - 082349
////////////////////////////////////////////////////////////////////////////////
unit java.util.PrimitiveIterator_OfDouble;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.function.DoubleConsumer,
  java.util.function.Consumer;

type
  JPrimitiveIterator_OfDouble = interface;

  JPrimitiveIterator_OfDoubleClass = interface(JObjectClass)
    ['{5E74E039-7773-4443-B3DF-CC9032C0C47A}']
    function next : JDouble; cdecl;                                             // ()Ljava/lang/Double; A: $1
    function nextDouble : Double; cdecl;                                        // ()D A: $401
    procedure forEachRemaining(action : JConsumer) ; cdecl; overload;           // (Ljava/util/function/Consumer;)V A: $1
    procedure forEachRemaining(action : JDoubleConsumer) ; cdecl; overload;     // (Ljava/util/function/DoubleConsumer;)V A: $1
  end;

  [JavaSignature('java/util/PrimitiveIterator_OfDouble')]
  JPrimitiveIterator_OfDouble = interface(JObject)
    ['{79DF585D-44E5-41A4-BE56-55EEA07B7846}']
    function next : JDouble; cdecl;                                             // ()Ljava/lang/Double; A: $1
    function nextDouble : Double; cdecl;                                        // ()D A: $401
    procedure forEachRemaining(action : JConsumer) ; cdecl; overload;           // (Ljava/util/function/Consumer;)V A: $1
    procedure forEachRemaining(action : JDoubleConsumer) ; cdecl; overload;     // (Ljava/util/function/DoubleConsumer;)V A: $1
  end;

  TJPrimitiveIterator_OfDouble = class(TJavaGenericImport<JPrimitiveIterator_OfDoubleClass, JPrimitiveIterator_OfDouble>)
  end;

implementation

end.
