//
// Generated by JavaToPas v1.5 20180804 - 082417
////////////////////////////////////////////////////////////////////////////////
unit javax.net.ssl.SSLEngineResult;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  javax.net.ssl.SSLEngineResult_Status,
  javax.net.ssl.SSLEngineResult_HandshakeStatus;

type
  JSSLEngineResult = interface;

  JSSLEngineResultClass = interface(JObjectClass)
    ['{4FDF895D-0E09-4525-AD65-2BC9FE1CA077}']
    function bytesConsumed : Integer; cdecl;                                    // ()I A: $11
    function bytesProduced : Integer; cdecl;                                    // ()I A: $11
    function getHandshakeStatus : JSSLEngineResult_HandshakeStatus; cdecl;      // ()Ljavax/net/ssl/SSLEngineResult$HandshakeStatus; A: $11
    function getStatus : JSSLEngineResult_Status; cdecl;                        // ()Ljavax/net/ssl/SSLEngineResult$Status; A: $11
    function init(status : JSSLEngineResult_Status; handshakeStatus : JSSLEngineResult_HandshakeStatus; bytesConsumed : Integer; bytesProduced : Integer) : JSSLEngineResult; cdecl;// (Ljavax/net/ssl/SSLEngineResult$Status;Ljavax/net/ssl/SSLEngineResult$HandshakeStatus;II)V A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('javax/net/ssl/SSLEngineResult$HandshakeStatus')]
  JSSLEngineResult = interface(JObject)
    ['{766424E1-ABB7-4CB3-9EC0-4D6E6BC9F31C}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJSSLEngineResult = class(TJavaGenericImport<JSSLEngineResultClass, JSSLEngineResult>)
  end;

implementation

end.
