//
// Generated by JavaToPas v1.5 20140918 - 093147
////////////////////////////////////////////////////////////////////////////////
unit android.media.ThumbnailUtils;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.graphics.Bitmap;

type
  JThumbnailUtils = interface;

  JThumbnailUtilsClass = interface(JObjectClass)
    ['{E1943B1C-B620-44F3-92D0-C94692959412}']
    function _GetOPTIONS_RECYCLE_INPUT : Integer; cdecl;                        //  A: $19
    function createVideoThumbnail(filePath : JString; kind : Integer) : JBitmap; cdecl;// (Ljava/lang/String;I)Landroid/graphics/Bitmap; A: $9
    function extractThumbnail(source : JBitmap; width : Integer; height : Integer) : JBitmap; cdecl; overload;// (Landroid/graphics/Bitmap;II)Landroid/graphics/Bitmap; A: $9
    function extractThumbnail(source : JBitmap; width : Integer; height : Integer; options : Integer) : JBitmap; cdecl; overload;// (Landroid/graphics/Bitmap;III)Landroid/graphics/Bitmap; A: $9
    function init : JThumbnailUtils; cdecl;                                     // ()V A: $1
    property OPTIONS_RECYCLE_INPUT : Integer read _GetOPTIONS_RECYCLE_INPUT;    // I A: $19
  end;

  [JavaSignature('android/media/ThumbnailUtils')]
  JThumbnailUtils = interface(JObject)
    ['{C858F80B-D5B9-4315-8186-660E2E37C86E}']
  end;

  TJThumbnailUtils = class(TJavaGenericImport<JThumbnailUtilsClass, JThumbnailUtils>)
  end;

const
  TJThumbnailUtilsOPTIONS_RECYCLE_INPUT = 2;

implementation

end.
