//
// Generated by JavaToPas v1.4 20140515 - 173619
////////////////////////////////////////////////////////////////////////////////
unit android.appwidget.AppWidgetHost;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.appwidget.AppWidgetHostView,
  android.appwidget.AppWidgetProviderInfo;

type
  JAppWidgetHost = interface;

  JAppWidgetHostClass = interface(JObjectClass)
    ['{3ED177CB-CED8-44C3-927A-6E8103D7C090}']
    function allocateAppWidgetId : Integer; cdecl;                              // ()I A: $1
    function createView(context : JContext; appWidgetId : Integer; appWidget : JAppWidgetProviderInfo) : JAppWidgetHostView; cdecl;// (Landroid/content/Context;ILandroid/appwidget/AppWidgetProviderInfo;)Landroid/appwidget/AppWidgetHostView; A: $11
    function init(context : JContext; hostId : Integer) : JAppWidgetHost; cdecl;// (Landroid/content/Context;I)V A: $1
    procedure deleteAllHosts ; cdecl;                                           // ()V A: $9
    procedure deleteAppWidgetId(appWidgetId : Integer) ; cdecl;                 // (I)V A: $1
    procedure deleteHost ; cdecl;                                               // ()V A: $1
    procedure startListening ; cdecl;                                           // ()V A: $1
    procedure stopListening ; cdecl;                                            // ()V A: $1
  end;

  [JavaSignature('android/appwidget/AppWidgetHost')]
  JAppWidgetHost = interface(JObject)
    ['{D1EC8655-E54F-434B-89F0-DB5409A1B8CA}']
    function allocateAppWidgetId : Integer; cdecl;                              // ()I A: $1
    procedure deleteAppWidgetId(appWidgetId : Integer) ; cdecl;                 // (I)V A: $1
    procedure deleteHost ; cdecl;                                               // ()V A: $1
    procedure startListening ; cdecl;                                           // ()V A: $1
    procedure stopListening ; cdecl;                                            // ()V A: $1
  end;

  TJAppWidgetHost = class(TJavaGenericImport<JAppWidgetHostClass, JAppWidgetHost>)
  end;

implementation

end.
