//
// Generated by JavaToPas v1.5 20140918 - 093109
////////////////////////////////////////////////////////////////////////////////
unit android.provider.ContactsContract_StreamItemPhotos;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JContactsContract_StreamItemPhotos = interface;

  JContactsContract_StreamItemPhotosClass = interface(JObjectClass)
    ['{2E3339D1-DDCB-460B-A5A6-50CC6D9065BF}']
    function _GetPHOTO : JString; cdecl;                                        //  A: $19
    property PHOTO : JString read _GetPHOTO;                                    // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/provider/ContactsContract_StreamItemPhotos')]
  JContactsContract_StreamItemPhotos = interface(JObject)
    ['{E5BCF0B6-8F8F-4E6F-AFD1-08543B75D933}']
  end;

  TJContactsContract_StreamItemPhotos = class(TJavaGenericImport<JContactsContract_StreamItemPhotosClass, JContactsContract_StreamItemPhotos>)
  end;

const
  TJContactsContract_StreamItemPhotosPHOTO = 'photo';

implementation

end.
