//
// Generated by JavaToPas v1.4 20140515 - 173603
////////////////////////////////////////////////////////////////////////////////
unit android.view.View_OnDragListener;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.view.DragEvent;

type
  JView_OnDragListener = interface;

  JView_OnDragListenerClass = interface(JObjectClass)
    ['{FCA9A933-B96C-47D7-914F-76C80DE4CF84}']
    function onDrag(JViewparam0 : JView; JDragEventparam1 : JDragEvent) : boolean; cdecl;// (Landroid/view/View;Landroid/view/DragEvent;)Z A: $401
  end;

  [JavaSignature('android/view/View_OnDragListener')]
  JView_OnDragListener = interface(JObject)
    ['{79B05E68-62FE-4956-81B2-29F2B7BF61B3}']
    function onDrag(JViewparam0 : JView; JDragEventparam1 : JDragEvent) : boolean; cdecl;// (Landroid/view/View;Landroid/view/DragEvent;)Z A: $401
  end;

  TJView_OnDragListener = class(TJavaGenericImport<JView_OnDragListenerClass, JView_OnDragListener>)
  end;

implementation

end.
