//
// Generated by JavaToPas v1.5 20140918 - 093129
////////////////////////////////////////////////////////////////////////////////
unit android.speech.RecognitionService;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.content.ClipData,
  Androidapi.JNI.os;

type
  JRecognitionService_Callback = interface; // merged
  JRecognitionService = interface;

  JRecognitionServiceClass = interface(JObjectClass)
    ['{DF89B525-D959-4C3E-B9B7-0FD5974C4021}']
    function _GetSERVICE_INTERFACE : JString; cdecl;                            //  A: $19
    function _GetSERVICE_META_DATA : JString; cdecl;                            //  A: $19
    function init : JRecognitionService; cdecl;                                 // ()V A: $1
    function onBind(intent : JIntent) : JIBinder; cdecl;                        // (Landroid/content/Intent;)Landroid/os/IBinder; A: $11
    procedure onDestroy ; cdecl;                                                // ()V A: $1
    property SERVICE_INTERFACE : JString read _GetSERVICE_INTERFACE;            // Ljava/lang/String; A: $19
    property SERVICE_META_DATA : JString read _GetSERVICE_META_DATA;            // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/speech/RecognitionService$Callback')]
  JRecognitionService = interface(JObject)
    ['{B94395F3-3A86-46DC-9E9C-F05C827F2EAC}']
    procedure onDestroy ; cdecl;                                                // ()V A: $1
  end;

  TJRecognitionService = class(TJavaGenericImport<JRecognitionServiceClass, JRecognitionService>)
  end;

  // Merged from: .\android-19\android.speech.RecognitionService_Callback.pas
  JRecognitionService_CallbackClass = interface(JObjectClass)
    ['{C3A81E1D-1287-4255-B4D1-E654B47D0FE2}']
    procedure beginningOfSpeech ; cdecl;                                        // ()V A: $1
    procedure bufferReceived(buffer : TJavaArray<Byte>) ; cdecl;                // ([B)V A: $1
    procedure endOfSpeech ; cdecl;                                              // ()V A: $1
    procedure error(error : Integer) ; cdecl;                                   // (I)V A: $1
    procedure partialResults(partialResults : JBundle) ; cdecl;                 // (Landroid/os/Bundle;)V A: $1
    procedure readyForSpeech(params : JBundle) ; cdecl;                         // (Landroid/os/Bundle;)V A: $1
    procedure results(results : JBundle) ; cdecl;                               // (Landroid/os/Bundle;)V A: $1
    procedure rmsChanged(rmsdB : Single) ; cdecl;                               // (F)V A: $1
  end;

  [JavaSignature('android/speech/RecognitionService_Callback')]
  JRecognitionService_Callback = interface(JObject)
    ['{B05E6B3F-00EA-42CE-BFB6-8997E38721E9}']
    procedure beginningOfSpeech ; cdecl;                                        // ()V A: $1
    procedure bufferReceived(buffer : TJavaArray<Byte>) ; cdecl;                // ([B)V A: $1
    procedure endOfSpeech ; cdecl;                                              // ()V A: $1
    procedure error(error : Integer) ; cdecl;                                   // (I)V A: $1
    procedure partialResults(partialResults : JBundle) ; cdecl;                 // (Landroid/os/Bundle;)V A: $1
    procedure readyForSpeech(params : JBundle) ; cdecl;                         // (Landroid/os/Bundle;)V A: $1
    procedure results(results : JBundle) ; cdecl;                               // (Landroid/os/Bundle;)V A: $1
    procedure rmsChanged(rmsdB : Single) ; cdecl;                               // (F)V A: $1
  end;

  TJRecognitionService_Callback = class(TJavaGenericImport<JRecognitionService_CallbackClass, JRecognitionService_Callback>)
  end;


const
  TJRecognitionServiceSERVICE_INTERFACE = 'android.speech.RecognitionService';
  TJRecognitionServiceSERVICE_META_DATA = 'android.speech';

implementation

end.
