//
// Generated by JavaToPas v1.4 20140515 - 173658
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.conn.params.ConnConnectionPNames;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JConnConnectionPNames = interface;

  JConnConnectionPNamesClass = interface(JObjectClass)
    ['{3CDF4A1E-50C0-4CB8-A6D0-A5FF6AA8948D}']
    function _GetMAX_STATUS_LINE_GARBAGE : JString; cdecl;                      //  A: $19
    property MAX_STATUS_LINE_GARBAGE : JString read _GetMAX_STATUS_LINE_GARBAGE;// Ljava/lang/String; A: $19
  end;

  [JavaSignature('org/apache/http/conn/params/ConnConnectionPNames')]
  JConnConnectionPNames = interface(JObject)
    ['{A8DCC90D-EDD7-44A2-88E2-9534EFC990DA}']
  end;

  TJConnConnectionPNames = class(TJavaGenericImport<JConnConnectionPNamesClass, JConnConnectionPNames>)
  end;

const
  TJConnConnectionPNamesMAX_STATUS_LINE_GARBAGE = 'http.connection.max-status-line-garbage';

implementation

end.
