//
// Generated by JavaToPas v1.4 20140515 - 173658
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.protocol.ResponseServer;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.apache.http.HttpResponse,
  org.apache.http.protocol.HttpContext;

type
  JResponseServer = interface;

  JResponseServerClass = interface(JObjectClass)
    ['{B3A81B5E-629C-4774-BBA5-7FE7A8229399}']
    function init : JResponseServer; cdecl;                                     // ()V A: $1
    procedure process(response : JHttpResponse; context : JHttpContext) ; cdecl;// (Lorg/apache/http/HttpResponse;Lorg/apache/http/protocol/HttpContext;)V A: $1
  end;

  [JavaSignature('org/apache/http/protocol/ResponseServer')]
  JResponseServer = interface(JObject)
    ['{2604AF14-8F12-4C8E-8475-45234F3DE9CE}']
    procedure process(response : JHttpResponse; context : JHttpContext) ; cdecl;// (Lorg/apache/http/HttpResponse;Lorg/apache/http/protocol/HttpContext;)V A: $1
  end;

  TJResponseServer = class(TJavaGenericImport<JResponseServerClass, JResponseServer>)
  end;

implementation

end.
