//
// Generated by JavaToPas v1.4 20140515 - 180521
////////////////////////////////////////////////////////////////////////////////
unit javax.xml.parsers.DocumentBuilder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.w3c.dom.DOMImplementation,
  org.w3c.dom.Document,
  org.xml.sax.InputSource,
  org.xml.sax.EntityResolver,
  org.xml.sax.ErrorHandler;

type
  JDocumentBuilder = interface;

  JDocumentBuilderClass = interface(JObjectClass)
    ['{48A2BE1D-97DC-4C0E-9A3A-80911BCA29D1}']
    function getDOMImplementation : JDOMImplementation; cdecl;                  // ()Lorg/w3c/dom/DOMImplementation; A: $401
    function isNamespaceAware : boolean; cdecl;                                 // ()Z A: $401
    function isValidating : boolean; cdecl;                                     // ()Z A: $401
    function isXIncludeAware : boolean; cdecl;                                  // ()Z A: $1
    function newDocument : JDocument; cdecl;                                    // ()Lorg/w3c/dom/Document; A: $401
    function parse(&file : JFile) : JDocument; cdecl; overload;                 // (Ljava/io/File;)Lorg/w3c/dom/Document; A: $1
    function parse(JInputSourceparam0 : JInputSource) : JDocument; cdecl; overload;// (Lorg/xml/sax/InputSource;)Lorg/w3c/dom/Document; A: $401
    function parse(stream : JInputStream) : JDocument; cdecl; overload;         // (Ljava/io/InputStream;)Lorg/w3c/dom/Document; A: $1
    function parse(stream : JInputStream; systemId : JString) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;)Lorg/w3c/dom/Document; A: $1
    function parse(uri : JString) : JDocument; cdecl; overload;                 // (Ljava/lang/String;)Lorg/w3c/dom/Document; A: $1
    procedure reset ; cdecl;                                                    // ()V A: $1
    procedure setEntityResolver(JEntityResolverparam0 : JEntityResolver) ; cdecl;// (Lorg/xml/sax/EntityResolver;)V A: $401
    procedure setErrorHandler(JErrorHandlerparam0 : JErrorHandler) ; cdecl;     // (Lorg/xml/sax/ErrorHandler;)V A: $401
  end;

  [JavaSignature('javax/xml/parsers/DocumentBuilder')]
  JDocumentBuilder = interface(JObject)
    ['{D3887A73-7666-4952-B157-42967AEEDE58}']
    function getDOMImplementation : JDOMImplementation; cdecl;                  // ()Lorg/w3c/dom/DOMImplementation; A: $401
    function isNamespaceAware : boolean; cdecl;                                 // ()Z A: $401
    function isValidating : boolean; cdecl;                                     // ()Z A: $401
    function isXIncludeAware : boolean; cdecl;                                  // ()Z A: $1
    function newDocument : JDocument; cdecl;                                    // ()Lorg/w3c/dom/Document; A: $401
    function parse(&file : JFile) : JDocument; cdecl; overload;                 // (Ljava/io/File;)Lorg/w3c/dom/Document; A: $1
    function parse(JInputSourceparam0 : JInputSource) : JDocument; cdecl; overload;// (Lorg/xml/sax/InputSource;)Lorg/w3c/dom/Document; A: $401
    function parse(stream : JInputStream) : JDocument; cdecl; overload;         // (Ljava/io/InputStream;)Lorg/w3c/dom/Document; A: $1
    function parse(stream : JInputStream; systemId : JString) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;)Lorg/w3c/dom/Document; A: $1
    function parse(uri : JString) : JDocument; cdecl; overload;                 // (Ljava/lang/String;)Lorg/w3c/dom/Document; A: $1
    procedure reset ; cdecl;                                                    // ()V A: $1
    procedure setEntityResolver(JEntityResolverparam0 : JEntityResolver) ; cdecl;// (Lorg/xml/sax/EntityResolver;)V A: $401
    procedure setErrorHandler(JErrorHandlerparam0 : JErrorHandler) ; cdecl;     // (Lorg/xml/sax/ErrorHandler;)V A: $401
  end;

  TJDocumentBuilder = class(TJavaGenericImport<JDocumentBuilderClass, JDocumentBuilder>)
  end;

implementation

end.
