//
// Generated by JavaToPas v1.4 20140515 - 180546
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.client.methods.HttpUriRequest;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHttpUriRequest = interface;

  JHttpUriRequestClass = interface(JObjectClass)
    ['{0B6D3FAC-FB0A-4EF5-AA3D-8BE97FD3B24D}']
    function getMethod : JString; cdecl;                                        // ()Ljava/lang/String; A: $401
    function getURI : JURI; cdecl;                                              // ()Ljava/net/URI; A: $401
    function isAborted : boolean; cdecl;                                        // ()Z A: $401
    procedure abort ; cdecl;                                                    // ()V A: $401
  end;

  [JavaSignature('org/apache/http/client/methods/HttpUriRequest')]
  JHttpUriRequest = interface(JObject)
    ['{6119EEF1-3D03-477E-8988-894DEC41CE7D}']
    function getMethod : JString; cdecl;                                        // ()Ljava/lang/String; A: $401
    function getURI : JURI; cdecl;                                              // ()Ljava/net/URI; A: $401
    function isAborted : boolean; cdecl;                                        // ()Z A: $401
    procedure abort ; cdecl;                                                    // ()V A: $401
  end;

  TJHttpUriRequest = class(TJavaGenericImport<JHttpUriRequestClass, JHttpUriRequest>)
  end;

implementation

end.
