//
// Generated by JavaToPas v1.4 20140526 - 132736
////////////////////////////////////////////////////////////////////////////////
unit java.util.ServiceConfigurationError;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JServiceConfigurationError = interface;

  JServiceConfigurationErrorClass = interface(JObjectClass)
    ['{3D291373-6083-49BA-A31B-CBB9645F0FBD}']
    function init(&message : JString) : JServiceConfigurationError; cdecl; overload;// (Ljava/lang/String;)V A: $1
    function init(&message : JString; cause : JThrowable) : JServiceConfigurationError; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('java/util/ServiceConfigurationError')]
  JServiceConfigurationError = interface(JObject)
    ['{A6B39613-CF25-45D6-ADF0-1F721604606B}']
  end;

  TJServiceConfigurationError = class(TJavaGenericImport<JServiceConfigurationErrorClass, JServiceConfigurationError>)
  end;

implementation

end.
