//
// Generated by JavaToPas v1.4 20140526 - 133908
////////////////////////////////////////////////////////////////////////////////
unit android.renderscript.Element_DataKind;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JElement_DataKind = interface;

  JElement_DataKindClass = interface(JObjectClass)
    ['{9BC772E4-1EC6-4815-AA66-B57F6DD942D8}']
    function _GetPIXEL_A : JElement_DataKind; cdecl;                            //  A: $4019
    function _GetPIXEL_L : JElement_DataKind; cdecl;                            //  A: $4019
    function _GetPIXEL_LA : JElement_DataKind; cdecl;                           //  A: $4019
    function _GetPIXEL_RGB : JElement_DataKind; cdecl;                          //  A: $4019
    function _GetPIXEL_RGBA : JElement_DataKind; cdecl;                         //  A: $4019
    function _GetUSER : JElement_DataKind; cdecl;                               //  A: $4019
    function valueOf(&name : JString) : JElement_DataKind; cdecl;               // (Ljava/lang/String;)Landroid/renderscript/Element$DataKind; A: $9
    function values : TJavaArray<JElement_DataKind>; cdecl;                     // ()[Landroid/renderscript/Element$DataKind; A: $9
    property PIXEL_A : JElement_DataKind read _GetPIXEL_A;                      // Landroid/renderscript/Element$DataKind; A: $4019
    property PIXEL_L : JElement_DataKind read _GetPIXEL_L;                      // Landroid/renderscript/Element$DataKind; A: $4019
    property PIXEL_LA : JElement_DataKind read _GetPIXEL_LA;                    // Landroid/renderscript/Element$DataKind; A: $4019
    property PIXEL_RGB : JElement_DataKind read _GetPIXEL_RGB;                  // Landroid/renderscript/Element$DataKind; A: $4019
    property PIXEL_RGBA : JElement_DataKind read _GetPIXEL_RGBA;                // Landroid/renderscript/Element$DataKind; A: $4019
    property USER : JElement_DataKind read _GetUSER;                            // Landroid/renderscript/Element$DataKind; A: $4019
  end;

  [JavaSignature('android/renderscript/Element_DataKind')]
  JElement_DataKind = interface(JObject)
    ['{FE713E82-F604-464C-BCC9-A52617D362B3}']
  end;

  TJElement_DataKind = class(TJavaGenericImport<JElement_DataKindClass, JElement_DataKind>)
  end;

implementation

end.
