//
// Generated by JavaToPas v1.4 20140526 - 133138
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.impl.io.HttpTransportMetricsImpl;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHttpTransportMetricsImpl = interface;

  JHttpTransportMetricsImplClass = interface(JObjectClass)
    ['{9909D736-E504-40BE-968B-7374DC1D67AE}']
    function getBytesTransferred : Int64; cdecl;                                // ()J A: $1
    function init : JHttpTransportMetricsImpl; cdecl;                           // ()V A: $1
    procedure incrementBytesTransferred(count : Int64) ; cdecl;                 // (J)V A: $1
    procedure reset ; cdecl;                                                    // ()V A: $1
    procedure setBytesTransferred(count : Int64) ; cdecl;                       // (J)V A: $1
  end;

  [JavaSignature('org/apache/http/impl/io/HttpTransportMetricsImpl')]
  JHttpTransportMetricsImpl = interface(JObject)
    ['{F8553646-4EBC-4B8A-B33F-EB3250D18A58}']
    function getBytesTransferred : Int64; cdecl;                                // ()J A: $1
    procedure incrementBytesTransferred(count : Int64) ; cdecl;                 // (J)V A: $1
    procedure reset ; cdecl;                                                    // ()V A: $1
    procedure setBytesTransferred(count : Int64) ; cdecl;                       // (J)V A: $1
  end;

  TJHttpTransportMetricsImpl = class(TJavaGenericImport<JHttpTransportMetricsImplClass, JHttpTransportMetricsImpl>)
  end;

implementation

end.
