//
// Generated by JavaToPas v1.4 20140526 - 133737
////////////////////////////////////////////////////////////////////////////////
unit android.gesture.GestureLibraries;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.gesture.GestureLibrary,
  Androidapi.JNI.GraphicsContentViewText;

type
  JGestureLibraries = interface;

  JGestureLibrariesClass = interface(JObjectClass)
    ['{D03C01AA-C88D-434B-B788-4B715A64E481}']
    function fromFile(path : JFile) : JGestureLibrary; cdecl; overload;         // (Ljava/io/File;)Landroid/gesture/GestureLibrary; A: $9
    function fromFile(path : JString) : JGestureLibrary; cdecl; overload;       // (Ljava/lang/String;)Landroid/gesture/GestureLibrary; A: $9
    function fromPrivateFile(context : JContext; &name : JString) : JGestureLibrary; cdecl;// (Landroid/content/Context;Ljava/lang/String;)Landroid/gesture/GestureLibrary; A: $9
    function fromRawResource(context : JContext; resourceId : Integer) : JGestureLibrary; cdecl;// (Landroid/content/Context;I)Landroid/gesture/GestureLibrary; A: $9
  end;

  [JavaSignature('android/gesture/GestureLibraries')]
  JGestureLibraries = interface(JObject)
    ['{76FB91CF-4335-48A3-A065-C3B0B0675C4C}']
  end;

  TJGestureLibraries = class(TJavaGenericImport<JGestureLibrariesClass, JGestureLibraries>)
  end;

implementation

end.
