//
// Generated by JavaToPas v1.5 20140918 - 132007
////////////////////////////////////////////////////////////////////////////////
unit android.widget.PopupMenu;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.view.Menu,
  android.view.MenuInflater,
  android.widget.PopupMenu_OnMenuItemClickListener;

type
  JPopupMenu_OnDismissListener = interface; // merged
  JPopupMenu = interface;

  JPopupMenuClass = interface(JObjectClass)
    ['{B2936616-CD38-4367-A637-8C7562DB4E23}']
    function getMenu : JMenu; cdecl;                                            // ()Landroid/view/Menu; A: $1
    function getMenuInflater : JMenuInflater; cdecl;                            // ()Landroid/view/MenuInflater; A: $1
    function init(context : JContext; anchor : JView) : JPopupMenu; cdecl;      // (Landroid/content/Context;Landroid/view/View;)V A: $1
    procedure dismiss ; cdecl;                                                  // ()V A: $1
    procedure inflate(menuRes : Integer) ; cdecl;                               // (I)V A: $1
    procedure setOnDismissListener(listener : JPopupMenu_OnDismissListener) ; cdecl;// (Landroid/widget/PopupMenu$OnDismissListener;)V A: $1
    procedure setOnMenuItemClickListener(listener : JPopupMenu_OnMenuItemClickListener) ; cdecl;// (Landroid/widget/PopupMenu$OnMenuItemClickListener;)V A: $1
    procedure show ; cdecl;                                                     // ()V A: $1
  end;

  [JavaSignature('android/widget/PopupMenu$OnMenuItemClickListener')]
  JPopupMenu = interface(JObject)
    ['{7ED48A97-D622-4086-AC61-878B9B7398A0}']
    function getMenu : JMenu; cdecl;                                            // ()Landroid/view/Menu; A: $1
    function getMenuInflater : JMenuInflater; cdecl;                            // ()Landroid/view/MenuInflater; A: $1
    procedure dismiss ; cdecl;                                                  // ()V A: $1
    procedure inflate(menuRes : Integer) ; cdecl;                               // (I)V A: $1
    procedure setOnDismissListener(listener : JPopupMenu_OnDismissListener) ; cdecl;// (Landroid/widget/PopupMenu$OnDismissListener;)V A: $1
    procedure setOnMenuItemClickListener(listener : JPopupMenu_OnMenuItemClickListener) ; cdecl;// (Landroid/widget/PopupMenu$OnMenuItemClickListener;)V A: $1
    procedure show ; cdecl;                                                     // ()V A: $1
  end;

  TJPopupMenu = class(TJavaGenericImport<JPopupMenuClass, JPopupMenu>)
  end;

  // Merged from: .\android-19\android.widget.PopupMenu_OnDismissListener.pas
  JPopupMenu_OnDismissListenerClass = interface(JObjectClass)
    ['{9CDB8A7A-2ECB-47F0-B300-C2E754C8B492}']
    procedure onDismiss(JPopupMenuparam0 : JPopupMenu) ; cdecl;                 // (Landroid/widget/PopupMenu;)V A: $401
  end;

  [JavaSignature('android/widget/PopupMenu_OnDismissListener')]
  JPopupMenu_OnDismissListener = interface(JObject)
    ['{372FB681-2775-4718-A8DF-930EF4318C6D}']
    procedure onDismiss(JPopupMenuparam0 : JPopupMenu) ; cdecl;                 // (Landroid/widget/PopupMenu;)V A: $401
  end;

  TJPopupMenu_OnDismissListener = class(TJavaGenericImport<JPopupMenu_OnDismissListenerClass, JPopupMenu_OnDismissListener>)
  end;


implementation

end.
