//
// Generated by JavaToPas v1.5 20140918 - 132054
////////////////////////////////////////////////////////////////////////////////
unit android.service.notification.StatusBarNotification;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os,
  android.app.Notification;

type
  JStatusBarNotification = interface;

  JStatusBarNotificationClass = interface(JObjectClass)
    ['{047ACFA1-E5A0-4D7D-8718-FFB072E6844F}']
    function _GetCREATOR : JParcelable_Creator; cdecl;                          //  A: $19
    function clone : JStatusBarNotification; cdecl;                             // ()Landroid/service/notification/StatusBarNotification; A: $1
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function getId : Integer; cdecl;                                            // ()I A: $1
    function getNotification : JNotification; cdecl;                            // ()Landroid/app/Notification; A: $1
    function getPackageName : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function getPostTime : Int64; cdecl;                                        // ()J A: $1
    function getTag : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function getUserId : Integer; cdecl;                                        // ()I A: $1
    function init(&in : JParcel) : JStatusBarNotification; cdecl; overload;     // (Landroid/os/Parcel;)V A: $1
    function init(pkg : JString; basePkg : JString; id : Integer; tag : JString; uid : Integer; initialPid : Integer; score : Integer; notification : JNotification; user : JUserHandle; postTime : Int64) : JStatusBarNotification; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;IIILandroid/app/Notification;Landroid/os/UserHandle;J)V A: $1
    function isClearable : boolean; cdecl;                                      // ()Z A: $1
    function isOngoing : boolean; cdecl;                                        // ()Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(&out : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
    property CREATOR : JParcelable_Creator read _GetCREATOR;                    // Landroid/os/Parcelable$Creator; A: $19
  end;

  [JavaSignature('android/service/notification/StatusBarNotification')]
  JStatusBarNotification = interface(JObject)
    ['{87977A14-4FD8-4AAA-B616-29DF7116D152}']
    function clone : JStatusBarNotification; cdecl;                             // ()Landroid/service/notification/StatusBarNotification; A: $1
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function getId : Integer; cdecl;                                            // ()I A: $1
    function getNotification : JNotification; cdecl;                            // ()Landroid/app/Notification; A: $1
    function getPackageName : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function getPostTime : Int64; cdecl;                                        // ()J A: $1
    function getTag : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function getUserId : Integer; cdecl;                                        // ()I A: $1
    function isClearable : boolean; cdecl;                                      // ()Z A: $1
    function isOngoing : boolean; cdecl;                                        // ()Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(&out : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  TJStatusBarNotification = class(TJavaGenericImport<JStatusBarNotificationClass, JStatusBarNotification>)
  end;

implementation

end.
