//
// Generated by JavaToPas v1.5 20140918 - 132110
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.impl.cookie.NetscapeDomainHandler;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.apache.http.cookie.Cookie,
  org.apache.http.cookie.CookieOrigin;

type
  JNetscapeDomainHandler = interface;

  JNetscapeDomainHandlerClass = interface(JObjectClass)
    ['{85D07206-4144-489C-B8D9-E9259BF74444}']
    function init : JNetscapeDomainHandler; cdecl;                              // ()V A: $1
    function match(cookie : JCookie; origin : JCookieOrigin) : boolean; cdecl;  // (Lorg/apache/http/cookie/Cookie;Lorg/apache/http/cookie/CookieOrigin;)Z A: $1
    procedure validate(cookie : JCookie; origin : JCookieOrigin) ; cdecl;       // (Lorg/apache/http/cookie/Cookie;Lorg/apache/http/cookie/CookieOrigin;)V A: $1
  end;

  [JavaSignature('org/apache/http/impl/cookie/NetscapeDomainHandler')]
  JNetscapeDomainHandler = interface(JObject)
    ['{F5547C8C-3CD2-4B1F-ABA5-5E8CDF2B71A2}']
    function match(cookie : JCookie; origin : JCookieOrigin) : boolean; cdecl;  // (Lorg/apache/http/cookie/Cookie;Lorg/apache/http/cookie/CookieOrigin;)Z A: $1
    procedure validate(cookie : JCookie; origin : JCookieOrigin) ; cdecl;       // (Lorg/apache/http/cookie/Cookie;Lorg/apache/http/cookie/CookieOrigin;)V A: $1
  end;

  TJNetscapeDomainHandler = class(TJavaGenericImport<JNetscapeDomainHandlerClass, JNetscapeDomainHandler>)
  end;

implementation

end.
