//
// Generated by JavaToPas v1.4 20140515 - 181040
////////////////////////////////////////////////////////////////////////////////
unit javax.xml.transform.sax.TransformerHandler;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  javax.xml.transform.Result,
  javax.xml.transform.Transformer;

type
  JTransformerHandler = interface;

  JTransformerHandlerClass = interface(JObjectClass)
    ['{4ECFD9B2-7BC6-4395-B3C3-B11EBECB24C4}']
    function getSystemId : JString; cdecl;                                      // ()Ljava/lang/String; A: $401
    function getTransformer : JTransformer; cdecl;                              // ()Ljavax/xml/transform/Transformer; A: $401
    procedure setResult(JResultparam0 : JResult) ; cdecl;                       // (Ljavax/xml/transform/Result;)V A: $401
    procedure setSystemId(JStringparam0 : JString) ; cdecl;                     // (Ljava/lang/String;)V A: $401
  end;

  [JavaSignature('javax/xml/transform/sax/TransformerHandler')]
  JTransformerHandler = interface(JObject)
    ['{3B1361B1-E7C4-48F1-B438-2FD9BD527413}']
    function getSystemId : JString; cdecl;                                      // ()Ljava/lang/String; A: $401
    function getTransformer : JTransformer; cdecl;                              // ()Ljavax/xml/transform/Transformer; A: $401
    procedure setResult(JResultparam0 : JResult) ; cdecl;                       // (Ljavax/xml/transform/Result;)V A: $401
    procedure setSystemId(JStringparam0 : JString) ; cdecl;                     // (Ljava/lang/String;)V A: $401
  end;

  TJTransformerHandler = class(TJavaGenericImport<JTransformerHandlerClass, JTransformerHandler>)
  end;

implementation

end.
