//
// Generated by JavaToPas v1.4 20140515 - 181041
////////////////////////////////////////////////////////////////////////////////
unit javax.xml.xpath.XPathFactoryConfigurationException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JXPathFactoryConfigurationException = interface;

  JXPathFactoryConfigurationExceptionClass = interface(JObjectClass)
    ['{6CE4F6E6-4D1D-4A44-893C-FB499B077517}']
    function init(&message : JString) : JXPathFactoryConfigurationException; cdecl; overload;// (Ljava/lang/String;)V A: $1
    function init(cause : JThrowable) : JXPathFactoryConfigurationException; cdecl; overload;// (Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('javax/xml/xpath/XPathFactoryConfigurationException')]
  JXPathFactoryConfigurationException = interface(JObject)
    ['{A613CEBD-BC90-4163-B46A-550934B4EA6F}']
  end;

  TJXPathFactoryConfigurationException = class(TJavaGenericImport<JXPathFactoryConfigurationExceptionClass, JXPathFactoryConfigurationException>)
  end;

implementation

end.
