//
// Generated by JavaToPas v1.4 20140515 - 181939
////////////////////////////////////////////////////////////////////////////////
unit org.apache.http.message.LineParser;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.apache.http.ProtocolVersion,
  org.apache.http.util.CharArrayBuffer,
  org.apache.http.message.ParserCursor,
  org.apache.http.RequestLine,
  org.apache.http.StatusLine,
  org.apache.http.Header;

type
  JLineParser = interface;

  JLineParserClass = interface(JObjectClass)
    ['{6DA0D437-4F2F-40AE-AF18-3E0BCD0E872E}']
    function hasProtocolVersion(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : boolean; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Z A: $401
    function parseHeader(JCharArrayBufferparam0 : JCharArrayBuffer) : JHeader; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;)Lorg/apache/http/Header; A: $401
    function parseProtocolVersion(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JProtocolVersion; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/ProtocolVersion; A: $401
    function parseRequestLine(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JRequestLine; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/RequestLine; A: $401
    function parseStatusLine(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JStatusLine; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/StatusLine; A: $401
  end;

  [JavaSignature('org/apache/http/message/LineParser')]
  JLineParser = interface(JObject)
    ['{2AC766A7-8BDB-4250-92DE-E1F87FE10861}']
    function hasProtocolVersion(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : boolean; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Z A: $401
    function parseHeader(JCharArrayBufferparam0 : JCharArrayBuffer) : JHeader; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;)Lorg/apache/http/Header; A: $401
    function parseProtocolVersion(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JProtocolVersion; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/ProtocolVersion; A: $401
    function parseRequestLine(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JRequestLine; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/RequestLine; A: $401
    function parseStatusLine(JCharArrayBufferparam0 : JCharArrayBuffer; JParserCursorparam1 : JParserCursor) : JStatusLine; cdecl;// (Lorg/apache/http/util/CharArrayBuffer;Lorg/apache/http/message/ParserCursor;)Lorg/apache/http/StatusLine; A: $401
  end;

  TJLineParser = class(TJavaGenericImport<JLineParserClass, JLineParser>)
  end;

implementation

end.
