//
// Generated by JavaToPas v1.5 20171018 - 170741
////////////////////////////////////////////////////////////////////////////////
unit java.util.concurrent.atomic.AtomicInteger;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.function.IntUnaryOperator,
  java.util.function.IntBinaryOperator;

type
  JAtomicInteger = interface;

  JAtomicIntegerClass = interface(JObjectClass)
    ['{055BC8A6-A184-4E38-B228-6A49CFFEC6C1}']
    function accumulateAndGet(x : Integer; accumulatorFunction : JIntBinaryOperator) : Integer; cdecl;// (ILjava/util/function/IntBinaryOperator;)I A: $11
    function addAndGet(delta : Integer) : Integer; cdecl;                       // (I)I A: $11
    function compareAndSet(expect : Integer; update : Integer) : boolean; cdecl;// (II)Z A: $11
    function decrementAndGet : Integer; cdecl;                                  // ()I A: $11
    function doubleValue : Double; cdecl;                                       // ()D A: $1
    function floatValue : Single; cdecl;                                        // ()F A: $1
    function get : Integer; cdecl;                                              // ()I A: $11
    function getAndAccumulate(x : Integer; accumulatorFunction : JIntBinaryOperator) : Integer; cdecl;// (ILjava/util/function/IntBinaryOperator;)I A: $11
    function getAndAdd(delta : Integer) : Integer; cdecl;                       // (I)I A: $11
    function getAndDecrement : Integer; cdecl;                                  // ()I A: $11
    function getAndIncrement : Integer; cdecl;                                  // ()I A: $11
    function getAndSet(newValue : Integer) : Integer; cdecl;                    // (I)I A: $11
    function getAndUpdate(updateFunction : JIntUnaryOperator) : Integer; cdecl; // (Ljava/util/function/IntUnaryOperator;)I A: $11
    function incrementAndGet : Integer; cdecl;                                  // ()I A: $11
    function init : JAtomicInteger; cdecl; overload;                            // ()V A: $1
    function init(initialValue : Integer) : JAtomicInteger; cdecl; overload;    // (I)V A: $1
    function intValue : Integer; cdecl;                                         // ()I A: $1
    function longValue : Int64; cdecl;                                          // ()J A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function updateAndGet(updateFunction : JIntUnaryOperator) : Integer; cdecl; // (Ljava/util/function/IntUnaryOperator;)I A: $11
    function weakCompareAndSet(expect : Integer; update : Integer) : boolean; cdecl;// (II)Z A: $11
    procedure &set(newValue : Integer) ; cdecl;                                 // (I)V A: $11
    procedure lazySet(newValue : Integer) ; cdecl;                              // (I)V A: $11
  end;

  [JavaSignature('java/util/concurrent/atomic/AtomicInteger')]
  JAtomicInteger = interface(JObject)
    ['{95CE52E7-B777-4572-BDCC-1818AF1A5ECF}']
    function doubleValue : Double; cdecl;                                       // ()D A: $1
    function floatValue : Single; cdecl;                                        // ()F A: $1
    function intValue : Integer; cdecl;                                         // ()I A: $1
    function longValue : Int64; cdecl;                                          // ()J A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJAtomicInteger = class(TJavaGenericImport<JAtomicIntegerClass, JAtomicInteger>)
  end;

implementation

end.
